// ==================================================
// SECTION: LOYALTY INTELLIGENCE
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  LoyaltyAccount,
  LoyaltyHistoryEntry,
  LoyaltyPurchaseHistoryEntry,
  LoyaltyReferralReward,
  LoyaltyReward,
  LoyaltyTier,
} from "@/components/loyaltyIntelligence/loyaltyTypes";

const NOW = new Date().toISOString();

export const LOYALTY_EXAMPLE_TIERS: LoyaltyTier[] = [
  {
    id: "bronze",
    name: "Bronze",
    minPoints: 0,
    minLifetimeSpendRub: 0,
    cashbackPercent: 1,
    bonusPointsMultiplier: 1,
    discountPercent: 0,
    perks: ["Накопление баллов", "Базовый cashback 1%"],
    sortOrder: 1,
  },
  {
    id: "silver",
    name: "Silver",
    minPoints: 500,
    minLifetimeSpendRub: 15000,
    cashbackPercent: 2,
    bonusPointsMultiplier: 1.2,
    discountPercent: 5,
    perks: ["Cashback 2%", "Скидка 5%", "Приоритетная доставка"],
    sortOrder: 2,
  },
  {
    id: "gold",
    name: "Gold",
    minPoints: 2000,
    minLifetimeSpendRub: 50000,
    cashbackPercent: 3,
    bonusPointsMultiplier: 1.5,
    discountPercent: 10,
    perks: ["Cashback 3%", "Скидка 10%", "VIP-поддержка", "Подарок к дню рождения"],
    sortOrder: 3,
  },
  {
    id: "platinum",
    name: "Platinum",
    minPoints: 5000,
    minLifetimeSpendRub: 120000,
    cashbackPercent: 5,
    bonusPointsMultiplier: 1.8,
    discountPercent: 12,
    perks: ["Cashback 5%", "Скидка 12%", "Бесплатная доставка", "Эксклюзивные букеты"],
    sortOrder: 4,
  },
  {
    id: "diamond",
    name: "Diamond",
    minPoints: 10000,
    minLifetimeSpendRub: 250000,
    cashbackPercent: 7,
    bonusPointsMultiplier: 2,
    discountPercent: 15,
    perks: [
      "Cashback 7%",
      "Скидка 15%",
      "Персональный флорист",
      "VIP Membership",
      "Ранний доступ к коллекциям",
    ],
    sortOrder: 5,
  },
];

export const LOYALTY_EXAMPLE_REWARDS: LoyaltyReward[] = [
  {
    id: "reward-cashback-base",
    kind: "cashback",
    title: "Base Cashback",
    description: "Базовый cashback на все покупки",
    value: 1,
    valueUnit: "percent",
    tierRestrictions: ["bronze", "silver", "gold", "platinum", "diamond"],
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: {},
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "reward-bonus-points",
    kind: "bonus_points",
    title: "Bonus Points",
    description: "1 балл за каждый рубль заказа",
    value: 1,
    valueUnit: "points",
    tierRestrictions: ["bronze", "silver", "gold", "platinum", "diamond"],
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: { pointsPerRub: 1 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "reward-referral",
    kind: "referral",
    title: "Referral Bonus",
    description: "500 баллов за приглашённого друга",
    value: 500,
    valueUnit: "points",
    tierRestrictions: ["bronze", "silver", "gold", "platinum", "diamond"],
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: { bonusRub: 500 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "reward-birthday",
    kind: "birthday",
    title: "Birthday Reward",
    description: "Персональный бонус в месяц дня рождения",
    value: 15,
    valueUnit: "percent",
    tierRestrictions: ["silver", "gold", "platinum", "diamond"],
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: { bonusPoints: 300, gift: "Мини-букет" },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "reward-vip-membership",
    kind: "vip_membership",
    title: "VIP Membership",
    description: "Эксклюзивный статус для Diamond-клиентов",
    value: 15,
    valueUnit: "percent",
    tierRestrictions: ["diamond"],
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: { vipLevel: 3 },
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const LOYALTY_EXAMPLE_PURCHASE_HISTORY: LoyaltyPurchaseHistoryEntry[] = [
  {
    id: "purchase-anna-001",
    customerId: "customer-anna-ivanova",
    orderId: "order-anna-001",
    totalRub: 6500,
    cashbackEarnedRub: 195,
    pointsEarned: 6500,
    tierAtPurchase: "gold",
    purchasedAt: "2026-05-10T14:30:00.000Z",
  },
  {
    id: "purchase-anna-002",
    customerId: "customer-anna-ivanova",
    orderId: "order-anna-002",
    totalRub: 4200,
    cashbackEarnedRub: 126,
    pointsEarned: 4200,
    tierAtPurchase: "gold",
    purchasedAt: "2026-04-02T11:00:00.000Z",
  },
];

export const LOYALTY_EXAMPLE_HISTORY: LoyaltyHistoryEntry[] = [
  {
    id: "history-anna-points-earned",
    customerId: "customer-anna-ivanova",
    kind: "points_earned",
    title: "Начисление баллов за заказ",
    amountRub: null,
    pointsDelta: 6500,
    relatedOrderId: "order-anna-001",
    occurredAt: "2026-05-10T14:30:00.000Z",
  },
  {
    id: "history-anna-cashback-earned",
    customerId: "customer-anna-ivanova",
    kind: "cashback_earned",
    title: "Cashback за заказ",
    amountRub: 195,
    pointsDelta: null,
    relatedOrderId: "order-anna-001",
    occurredAt: "2026-05-10T14:30:00.000Z",
  },
  {
    id: "history-anna-tier-upgrade",
    customerId: "customer-anna-ivanova",
    kind: "tier_upgrade",
    title: "Повышение до Gold",
    amountRub: null,
    pointsDelta: null,
    relatedOrderId: null,
    occurredAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "history-anna-birthday",
    customerId: "customer-anna-ivanova",
    kind: "birthday_bonus",
    title: "Birthday bonus",
    amountRub: null,
    pointsDelta: 300,
    relatedOrderId: null,
    occurredAt: "2026-05-01T08:00:00.000Z",
  },
];

export const LOYALTY_EXAMPLE_REFERRALS: LoyaltyReferralReward[] = [
  {
    id: "referral-anna-001",
    referrerCustomerId: "customer-anna-ivanova",
    referredCustomerId: "customer-maria-petrova",
    referralCode: "ANNA-REF-2026",
    bonusPoints: 500,
    bonusRub: 500,
    status: "completed",
    createdAt: "2026-02-01T10:00:00.000Z",
    completedAt: "2026-02-15T12:00:00.000Z",
  },
];

function buildAnnaAccount(): LoyaltyAccount {
  const customerId = "customer-anna-ivanova";

  return {
    customerId,
    fullName: "Анна Иванова",
    phone: "+7 999 111-22-33",
    tierId: "gold",
    points: {
      customerId,
      availablePoints: 10700,
      pendingPoints: 0,
      lifetimeEarnedPoints: 10700,
      lifetimeRedeemedPoints: 0,
      updatedAt: NOW,
    },
    cashback: {
      customerId,
      availableRub: 321,
      pendingRub: 0,
      lifetimeEarnedRub: 321,
      lifetimeRedeemedRub: 0,
      updatedAt: NOW,
    },
    vipMembership: null,
    birthdayReward: {
      id: "birthday-anna",
      customerId,
      birthMonth: 5,
      bonusPoints: 300,
      discountPercent: 15,
      giftDescription: "Мини-букет",
      status: "active",
      grantedAt: "2026-05-01T08:00:00.000Z",
      expiresAt: "2026-05-31T23:59:59.000Z",
    },
    referralCode: "ANNA-REF-2026",
    statistics: {
      customerId,
      currentTierId: "gold",
      totalPoints: 10700,
      totalCashbackRub: 321,
      totalReferrals: 1,
      birthdayRewardsClaimed: 1,
      tierUpgrades: 2,
      purchaseCount: 2,
      lastPurchaseAt: "2026-05-10T14:30:00.000Z",
      firstPurchaseAt: "2026-04-02T11:00:00.000Z",
      repeatPurchaseScore: 65,
      calculatedAt: NOW,
    },
    lifetimeValue: {
      customerId,
      totalSpendRub: 10700,
      totalOrders: 2,
      averageOrderValueRub: 5350,
      projectedAnnualValueRub: 64200,
      loyaltyScore: 72,
      tierId: "gold",
      calculatedAt: NOW,
    },
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: NOW,
  };
}

function buildDiamondAccount(): LoyaltyAccount {
  const customerId = "customer-elena-diamond";

  return {
    customerId,
    fullName: "Елена Смирнова",
    phone: "+7 999 555-66-77",
    tierId: "diamond",
    points: {
      customerId,
      availablePoints: 28500,
      pendingPoints: 500,
      lifetimeEarnedPoints: 32000,
      lifetimeRedeemedPoints: 3500,
      updatedAt: NOW,
    },
    cashback: {
      customerId,
      availableRub: 1850,
      pendingRub: 120,
      lifetimeEarnedRub: 9200,
      lifetimeRedeemedRub: 7350,
      updatedAt: NOW,
    },
    vipMembership: {
      customerId,
      tierId: "diamond",
      status: "active",
      memberSince: "2025-11-01T00:00:00.000Z",
      expiresAt: null,
      perks: ["Персональный флорист", "Ранний доступ", "VIP Membership"],
      updatedAt: NOW,
    },
    birthdayReward: null,
    referralCode: "ELENA-VIP-2025",
    statistics: {
      customerId,
      currentTierId: "diamond",
      totalPoints: 28500,
      totalCashbackRub: 1850,
      totalReferrals: 3,
      birthdayRewardsClaimed: 2,
      tierUpgrades: 4,
      purchaseCount: 18,
      lastPurchaseAt: "2026-06-20T16:00:00.000Z",
      firstPurchaseAt: "2024-08-10T12:00:00.000Z",
      repeatPurchaseScore: 95,
      calculatedAt: NOW,
    },
    lifetimeValue: {
      customerId,
      totalSpendRub: 285000,
      totalOrders: 18,
      averageOrderValueRub: 15833,
      projectedAnnualValueRub: 190000,
      loyaltyScore: 96,
      tierId: "diamond",
      calculatedAt: NOW,
    },
    createdAt: "2024-08-10T12:00:00.000Z",
    updatedAt: NOW,
  };
}

export const LOYALTY_EXAMPLE_ACCOUNTS: LoyaltyAccount[] = [
  buildAnnaAccount(),
  buildDiamondAccount(),
];

export function buildLoyaltyExampleRegistryState() {
  return {
    tiers: [...LOYALTY_EXAMPLE_TIERS],
    rewards: [...LOYALTY_EXAMPLE_REWARDS],
    accounts: [...LOYALTY_EXAMPLE_ACCOUNTS],
    purchaseHistory: [...LOYALTY_EXAMPLE_PURCHASE_HISTORY],
    history: [...LOYALTY_EXAMPLE_HISTORY],
    referrals: [...LOYALTY_EXAMPLE_REFERRALS],
  };
}
