// ==================================================
// SECTION: SEARCH INTELLIGENCE
// РАЗДЕЛ: Public foundation exports
// ==================================================
export type {
  SearchResultKind,
  SearchSuggestionKind,
  SearchSynonymDirection,
  SearchRankingSignal,
  SearchAiPreparationStatus,
  SearchIndexEntry,
  SearchSuggestion,
  SearchSynonym,
  SearchTypoCorrection,
  SearchRankingRule,
  SearchPopularQuery,
  SearchRelatedQuery,
  SearchHistoryEntry,
  SearchAnalyticsEvent,
  SearchAiPreparation,
  SearchQueryResult,
  SearchStatistics,
  SearchIntelligenceSnapshot,
  SearchListFilters,
  SearchRegistryState,
  SearchReadOnlySummary,
  SmartSearchOptions,
} from "@/components/searchIntelligence/searchTypes";

export {
  SEARCH_EXAMPLE_INDEX,
  SEARCH_EXAMPLE_SUGGESTIONS,
  SEARCH_EXAMPLE_SYNONYMS,
  SEARCH_EXAMPLE_TYPO_CORRECTIONS,
  SEARCH_EXAMPLE_RANKING_RULES,
  SEARCH_EXAMPLE_POPULAR_QUERIES,
  SEARCH_EXAMPLE_RELATED_QUERIES,
  SEARCH_EXAMPLE_HISTORY,
  SEARCH_EXAMPLE_ANALYTICS,
  SEARCH_EXAMPLE_AI_PREPARATIONS,
  buildSearchExampleRegistryState,
} from "@/components/searchIntelligence/searchExamples";

export {
  SEARCH_INDEX_STORAGE_KEY,
  SEARCH_SYNONYM_STORAGE_KEY,
  SEARCH_TYPO_STORAGE_KEY,
  normalizeSearchToken,
  listSearchIndexEntries,
  listSearchIndexByEntity,
  listSearchIndexByKind,
  registerSearchIndexEntry,
  listSearchSynonyms,
  resolveSynonymsForTerm,
  registerSearchSynonym,
  listTypoCorrections,
  correctSearchTypo,
  registerTypoCorrection,
  seedSearchIndexRegistry,
  clearSearchIndexRegistry,
  matchSearchIndex,
} from "@/components/searchIntelligence/searchIndexRegistry";

export {
  SEARCH_SUGGESTION_STORAGE_KEY,
  SEARCH_POPULAR_STORAGE_KEY,
  SEARCH_RELATED_STORAGE_KEY,
  SEARCH_HISTORY_STORAGE_KEY,
  listSearchSuggestions,
  listAutocompleteSuggestions,
  listPopularSearches,
  listAllRelatedQueries,
  listRelatedQueries,
  listSearchHistory,
  listRecentSearchSuggestions,
  registerSearchSuggestion,
  registerPopularQuery,
  registerRelatedQuery,
  appendSearchHistoryEntry,
  seedSearchSuggestionRegistry,
  clearSearchSuggestionRegistry,
} from "@/components/searchIntelligence/searchSuggestionRegistry";

export {
  SEARCH_RANKING_STORAGE_KEY,
  SEARCH_ANALYTICS_STORAGE_KEY,
  SEARCH_AI_STORAGE_KEY,
  listSearchRankingRules,
  getSearchRankingRuleBySignal,
  applySearchRanking,
  listSearchAnalyticsEvents,
  listSearchAnalyticsByKind,
  calculateSearchAnalyticsSummary,
  listAiSearchPreparations,
  getAiSearchPreparationById,
  registerSearchRankingRule,
  registerSearchAnalyticsEvent,
  registerAiSearchPreparation,
  seedSearchRankingRegistry,
  clearSearchRankingRegistry,
  inferRankingSignals,
} from "@/components/searchIntelligence/searchRankingRegistry";

export {
  SEARCH_INTELLIGENCE_STORAGE_KEY,
  smartSearch,
  calculateSearchStatistics,
  buildSearchIntelligenceSnapshot,
  initializeSearchIntelligence,
  getSearchIntelligenceExample,
  getSearchReadOnlySummary,
  readSearchFoundationCapabilities,
  SEARCH_INTELLIGENCE_ENGINE_SCHEMA,
  listAllSearchFoundationCapabilities,
} from "@/components/searchIntelligence/searchEngine";
