// ==================================================
// SECTION: INTEGRATION INTELLIGENCE
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  ExternalApiEntry,
  FutureConnector,
  IntegrationBridge,
  IntegrationHealthMetric,
  RetryQueueEntry,
  SyncQueueEntry,
  WebhookEntry,
} from "@/components/integrationIntelligence/integrationTypes";

const NOW = new Date().toISOString();

export const INTEGRATION_EXAMPLE_BRIDGES: IntegrationBridge[] = [
  {
    id: "bridge-crm",
    kind: "crm",
    name: "CRM Bridge",
    description: "Read-only bridge to CRM Intelligence customer profiles",
    direction: "bidirectional",
    status: "pending",
    sourceModule: "integrationIntelligence",
    targetModule: "crmIntelligence",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-order",
    kind: "order",
    name: "Order Bridge",
    description: "Read-only bridge to Order Engine order store",
    direction: "inbound",
    status: "pending",
    sourceModule: "orderIntelligence",
    targetModule: "integrationIntelligence",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-checkout",
    kind: "checkout",
    name: "Checkout Bridge",
    description: "Future bridge for checkout payload and validation sync",
    direction: "outbound",
    status: "inactive",
    sourceModule: "integrationIntelligence",
    targetModule: "checkout",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-telegram",
    kind: "telegram",
    name: "Telegram Bridge",
    description: "Future bridge for Telegram bot notifications and order updates",
    direction: "outbound",
    status: "inactive",
    sourceModule: "integrationIntelligence",
    targetModule: "telegram",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-payment",
    kind: "payment",
    name: "Payment Bridge",
    description: "Future bridge for payment provider webhooks and status sync",
    direction: "bidirectional",
    status: "inactive",
    sourceModule: "integrationIntelligence",
    targetModule: "payment",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-inventory",
    kind: "inventory",
    name: "Inventory Bridge",
    description: "Read-only bridge to Inventory Engine stock levels",
    direction: "inbound",
    status: "pending",
    sourceModule: "inventoryIntelligence",
    targetModule: "integrationIntelligence",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-courier",
    kind: "courier",
    name: "Courier Bridge",
    description: "Read-only bridge to Courier Engine dispatch status",
    direction: "inbound",
    status: "pending",
    sourceModule: "courierIntelligence",
    targetModule: "integrationIntelligence",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-delivery",
    kind: "delivery",
    name: "Delivery Bridge",
    description: "Read-only bridge to Delivery Engine zone and tracking data",
    direction: "inbound",
    status: "pending",
    sourceModule: "deliveryIntelligence",
    targetModule: "integrationIntelligence",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-analytics",
    kind: "analytics",
    name: "Analytics Bridge",
    description: "Read-only bridge to Analytics Intelligence events",
    direction: "outbound",
    status: "pending",
    sourceModule: "integrationIntelligence",
    targetModule: "analyticsIntelligence",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
  {
    id: "bridge-ai",
    kind: "ai",
    name: "AI Bridge",
    description: "Future bridge to AI Brain suggestions and preparation hooks",
    direction: "bidirectional",
    status: "inactive",
    sourceModule: "integrationIntelligence",
    targetModule: "aiBrain",
    wired: false,
    readOnly: true,
    lastSyncAt: null,
    errorCount: 0,
    updatedAt: NOW,
  },
];

export const INTEGRATION_EXAMPLE_EXTERNAL_APIS: ExternalApiEntry[] = [
  {
    id: "api-yandex-geocode",
    name: "Yandex Geocoder",
    provider: "Yandex",
    baseUrl: "https://geocode-maps.yandex.ru/1.x",
    version: "1.x",
    status: "active",
    authType: "api_key",
    rateLimitPerMinute: 60,
    timeoutMs: 5000,
    wired: false,
    updatedAt: NOW,
  },
  {
    id: "api-yandex-suggest",
    name: "Yandex Suggest",
    provider: "Yandex",
    baseUrl: "https://suggest-maps.yandex.ru/v1/suggest",
    version: "v1",
    status: "active",
    authType: "api_key",
    rateLimitPerMinute: 120,
    timeoutMs: 3000,
    wired: false,
    updatedAt: NOW,
  },
  {
    id: "api-telegram-bot",
    name: "Telegram Bot API",
    provider: "Telegram",
    baseUrl: "https://api.telegram.org",
    version: "bot",
    status: "inactive",
    authType: "bearer",
    rateLimitPerMinute: 30,
    timeoutMs: 10000,
    wired: false,
    updatedAt: NOW,
  },
];

export const INTEGRATION_EXAMPLE_WEBHOOKS: WebhookEntry[] = [
  {
    id: "webhook-order-created",
    name: "Order Created",
    eventType: "order.created",
    targetUrl: "/api/webhooks/order-created",
    status: "inactive",
    secretConfigured: false,
    lastTriggeredAt: null,
    successCount: 0,
    failureCount: 0,
    wired: false,
    updatedAt: NOW,
  },
  {
    id: "webhook-payment-confirmed",
    name: "Payment Confirmed",
    eventType: "payment.confirmed",
    targetUrl: "/api/webhooks/payment-confirmed",
    status: "inactive",
    secretConfigured: false,
    lastTriggeredAt: null,
    successCount: 0,
    failureCount: 0,
    wired: false,
    updatedAt: NOW,
  },
  {
    id: "webhook-delivery-status",
    name: "Delivery Status Changed",
    eventType: "delivery.status_changed",
    targetUrl: "/api/webhooks/delivery-status",
    status: "paused",
    secretConfigured: true,
    lastTriggeredAt: null,
    successCount: 0,
    failureCount: 0,
    wired: false,
    updatedAt: NOW,
  },
];

export const INTEGRATION_EXAMPLE_SYNC_QUEUE: SyncQueueEntry[] = [
  {
    id: "sync-001",
    bridgeId: "bridge-order",
    bridgeKind: "order",
    operation: "sync_orders_snapshot",
    payloadSummary: "Foundation seed — no live payload",
    status: "pending",
    priority: 1,
    scheduledAt: NOW,
    processedAt: null,
    errorMessage: null,
    createdAt: NOW,
  },
  {
    id: "sync-002",
    bridgeId: "bridge-crm",
    bridgeKind: "crm",
    operation: "sync_customer_profiles",
    payloadSummary: "Foundation seed — no live payload",
    status: "pending",
    priority: 2,
    scheduledAt: NOW,
    processedAt: null,
    errorMessage: null,
    createdAt: NOW,
  },
  {
    id: "sync-003",
    bridgeId: "bridge-analytics",
    bridgeKind: "analytics",
    operation: "push_integration_event",
    payloadSummary: "Foundation seed — integration.health_check",
    status: "completed",
    priority: 3,
    scheduledAt: "2026-06-24T10:00:00.000Z",
    processedAt: "2026-06-24T10:00:01.000Z",
    errorMessage: null,
    createdAt: "2026-06-24T09:59:00.000Z",
  },
];

export const INTEGRATION_EXAMPLE_RETRY_QUEUE: RetryQueueEntry[] = [
  {
    id: "retry-001",
    syncQueueId: "sync-001",
    bridgeId: "bridge-order",
    attempt: 1,
    maxAttempts: 3,
    status: "pending",
    nextRetryAt: NOW,
    lastError: null,
    createdAt: NOW,
  },
];

export const INTEGRATION_EXAMPLE_HEALTH: IntegrationHealthMetric[] = [
  {
    id: "health-overall",
    bridgeId: null,
    bridgeKind: null,
    level: "healthy",
    label: "Integration Foundation",
    message: "All bridges registered — none wired yet (foundation mode)",
    latencyMs: null,
    uptimePercent: 100,
    checkedAt: NOW,
  },
  {
    id: "health-bridge-order",
    bridgeId: "bridge-order",
    bridgeKind: "order",
    level: "unknown",
    label: "Order Bridge",
    message: "Pending wiring — read-only foundation",
    latencyMs: null,
    uptimePercent: null,
    checkedAt: NOW,
  },
  {
    id: "health-bridge-crm",
    bridgeId: "bridge-crm",
    bridgeKind: "crm",
    level: "unknown",
    label: "CRM Bridge",
    message: "Pending wiring — read-only foundation",
    latencyMs: null,
    uptimePercent: null,
    checkedAt: NOW,
  },
];

export const INTEGRATION_EXAMPLE_FUTURE_CONNECTORS: FutureConnector[] = [
  {
    id: "connector-1c",
    name: "1C Accounting Export",
    kind: "external",
    description: "Future connector for finance and supplier cost export to 1C",
    status: "planned",
    targetModule: "financeIntelligence",
    estimatedWiringStage: "Stage 45+",
    dependencies: ["bridge-order", "bridge-payment"],
    createdAt: NOW,
  },
  {
    id: "connector-amocrm",
    name: "AmoCRM Sync",
    kind: "crm",
    description: "Future bidirectional CRM sync for external AmoCRM instance",
    status: "in_design",
    targetModule: "crmIntelligence",
    estimatedWiringStage: "Stage 42+",
    dependencies: ["bridge-crm"],
    createdAt: NOW,
  },
  {
    id: "connector-payment-yookassa",
    name: "YooKassa Payment",
    kind: "payment",
    description: "Payment provider connector for checkout confirmation webhooks",
    status: "ready_for_wiring",
    targetModule: "checkout",
    estimatedWiringStage: "Stage 40+",
    dependencies: ["bridge-payment", "bridge-checkout"],
    createdAt: NOW,
  },
];

export function buildIntegrationExampleRegistryState() {
  return {
    bridges: [...INTEGRATION_EXAMPLE_BRIDGES],
    externalApis: [...INTEGRATION_EXAMPLE_EXTERNAL_APIS],
    webhooks: [...INTEGRATION_EXAMPLE_WEBHOOKS],
    syncQueue: [...INTEGRATION_EXAMPLE_SYNC_QUEUE],
    retryQueue: [...INTEGRATION_EXAMPLE_RETRY_QUEUE],
    health: [...INTEGRATION_EXAMPLE_HEALTH],
    futureConnectors: [...INTEGRATION_EXAMPLE_FUTURE_CONNECTORS],
  };
}
