// ==================================================
// SECTION: INTEGRATION INTELLIGENCE
// РАЗДЕЛ: Public foundation exports
// ==================================================
export type {
  BridgeKind,
  BridgeStatus,
  BridgeDirection,
  ExternalApiStatus,
  WebhookStatus,
  SyncQueueStatus,
  RetryQueueStatus,
  IntegrationHealthLevel,
  FutureConnectorStatus,
  IntegrationBridge,
  ExternalApiEntry,
  WebhookEntry,
  SyncQueueEntry,
  RetryQueueEntry,
  IntegrationHealthMetric,
  FutureConnector,
  IntegrationStatistics,
  IntegrationIntelligenceSnapshot,
  BridgeListFilters,
  IntegrationRegistryState,
  IntegrationReadOnlySummary,
} from "@/components/integrationIntelligence/integrationTypes";

export {
  INTEGRATION_EXAMPLE_BRIDGES,
  INTEGRATION_EXAMPLE_EXTERNAL_APIS,
  INTEGRATION_EXAMPLE_WEBHOOKS,
  INTEGRATION_EXAMPLE_SYNC_QUEUE,
  INTEGRATION_EXAMPLE_RETRY_QUEUE,
  INTEGRATION_EXAMPLE_HEALTH,
  INTEGRATION_EXAMPLE_FUTURE_CONNECTORS,
  buildIntegrationExampleRegistryState,
} from "@/components/integrationIntelligence/integrationExamples";

export {
  INTEGRATION_BRIDGE_STORAGE_KEY,
  listBridges,
  getBridgeById,
  getBridgeByKind,
  listActiveBridges,
  listPendingBridges,
  listWiredBridges,
  listUnwiredBridges,
  listBridgesByStatus,
  getCrmBridge,
  getOrderBridge,
  getCheckoutBridge,
  getTelegramBridge,
  getPaymentBridge,
  getInventoryBridge,
  getCourierBridge,
  getDeliveryBridge,
  getAnalyticsBridge,
  getAiBridge,
  registerBridge,
  seedBridgeRegistry,
  clearBridgeRegistry,
  buildBridgeRegistrySummary,
} from "@/components/integrationIntelligence/bridgeRegistry";

export {
  INTEGRATION_EXTERNAL_API_STORAGE_KEY,
  INTEGRATION_WEBHOOK_STORAGE_KEY,
  listExternalApis,
  getExternalApiById,
  listActiveExternalApis,
  listWebhooks,
  getWebhookById,
  getWebhookByEventType,
  registerExternalApi,
  registerWebhook,
  seedIntegrationRegistry,
  clearIntegrationRegistry,
} from "@/components/integrationIntelligence/integrationRegistry";

export {
  INTEGRATION_SYNC_QUEUE_STORAGE_KEY,
  INTEGRATION_RETRY_QUEUE_STORAGE_KEY,
  listSyncQueue,
  getSyncQueueEntryById,
  listSyncQueueByBridge,
  listSyncQueueByKind,
  listPendingSyncQueue,
  listFailedSyncQueue,
  listRetryQueue,
  getRetryQueueEntryById,
  listRetryQueueBySyncId,
  listPendingRetryQueue,
  listScheduledRetryQueue,
  registerSyncQueueEntry,
  registerRetryQueueEntry,
  seedSyncEngine,
  clearSyncEngine,
  buildSyncQueueSummary,
  estimateNextRetryDelay,
} from "@/components/integrationIntelligence/syncEngine";

export {
  INTEGRATION_HEALTH_STORAGE_KEY,
  INTEGRATION_FUTURE_CONNECTOR_STORAGE_KEY,
  resolveOverallHealthLevel,
  listIntegrationHealth,
  getIntegrationHealthById,
  getOverallIntegrationHealth,
  listFutureConnectors,
  getFutureConnectorById,
  calculateIntegrationStatistics,
  registerIntegrationHealthMetric,
  registerFutureConnector,
  seedIntegrationMetrics,
  clearIntegrationMetrics,
  buildIntegrationHealthReport,
} from "@/components/integrationIntelligence/integrationMetrics";

export {
  INTEGRATION_INTELLIGENCE_STORAGE_KEY,
  buildIntegrationIntelligenceSnapshot,
  initializeIntegrationIntelligence,
  getIntegrationIntelligenceExample,
  getIntegrationReadOnlySummary,
  readIntegrationFoundationCapabilities,
  INTEGRATION_INTELLIGENCE_ENGINE_SCHEMA,
  listAllIntegrationFoundationCapabilities,
} from "@/components/integrationIntelligence/integrationEngine";
