// ==================================================
// SECTION: PROMOTION INTELLIGENCE
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  AiPromotionSuggestion,
  FeaturedProductPromotion,
  LoyaltyProgram,
  MarketingCampaign,
  PromotionBanner,
  PromotionCoupon,
  PromotionRule,
  ScheduledPromotion,
} from "@/components/promotionIntelligence/promotionTypes";

const NOW = new Date().toISOString();

export const PROMOTION_EXAMPLE_RULES: PromotionRule[] = [
  {
    id: "rule-min-order-3000",
    kind: "promo_code",
    condition: "min_order_rub",
    operator: "gte",
    value: 3000,
    priority: 10,
    label: "Минимальная сумма заказа 3000 ₽",
  },
  {
    id: "rule-vip-level-2",
    kind: "vip_discount",
    condition: "vip_level",
    operator: "gte",
    value: 2,
    priority: 20,
    label: "VIP level 2+",
  },
  {
    id: "rule-birthday-month",
    kind: "birthday_discount",
    condition: "birthday_month",
    operator: "eq",
    value: 0,
    priority: 15,
    label: "Месяц дня рождения клиента",
  },
  {
    id: "rule-happy-hour",
    kind: "happy_hour",
    condition: "hour_range",
    operator: "between",
    value: ["14", "17"],
    priority: 5,
    label: "Happy hour 14:00–17:00",
  },
  {
    id: "rule-season-spring",
    kind: "seasonal",
    condition: "season",
    operator: "eq",
    value: "spring",
    priority: 8,
    label: "Весенний сезон",
  },
];

export const PROMOTION_EXAMPLE_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: "campaign-spring-bloom",
    slug: "spring-bloom",
    title: "Spring Bloom",
    description: "Весенняя сезонная кампания с акцентом на тюльпаны и пионы",
    kind: "seasonal",
    status: "active",
    scope: "order",
    startsAt: "2026-03-01T00:00:00.000Z",
    endsAt: "2026-05-31T23:59:59.000Z",
    rules: [PROMOTION_EXAMPLE_RULES[4]],
    bannerIds: ["banner-spring-hero"],
    couponIds: ["coupon-spring10"],
    featuredProductIds: ["product-tulip-classic", "product-peony-premium"],
    priority: 10,
    tags: ["seasonal", "spring"],
    metadata: { season: "spring" },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "campaign-flash-weekend",
    slug: "flash-weekend",
    title: "Flash Weekend",
    description: "Flash sale на выходные — ограниченное время",
    kind: "flash_sale",
    status: "scheduled",
    scope: "order",
    startsAt: "2026-06-28T00:00:00.000Z",
    endsAt: "2026-06-29T23:59:59.000Z",
    rules: [PROMOTION_EXAMPLE_RULES[0]],
    bannerIds: ["banner-flash-hero"],
    couponIds: ["coupon-flash15"],
    featuredProductIds: [],
    priority: 20,
    tags: ["flash_sale"],
    metadata: { discountPercent: 15 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "campaign-vip-loyalty",
    slug: "vip-loyalty",
    title: "VIP Loyalty",
    description: "Постоянная VIP-скидка для лояльных клиентов",
    kind: "vip_discount",
    status: "active",
    scope: "customer_segment",
    startsAt: "2026-01-01T00:00:00.000Z",
    endsAt: null,
    rules: [PROMOTION_EXAMPLE_RULES[1]],
    bannerIds: [],
    couponIds: ["coupon-vip10"],
    featuredProductIds: [],
    priority: 5,
    tags: ["vip", "loyalty"],
    metadata: { vipDiscountPercent: 10 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "campaign-free-delivery-base",
    slug: "free-delivery-base",
    title: "Free Delivery Base Zone",
    description: "Бесплатная доставка в базовой зоне от 5000 ₽",
    kind: "free_delivery",
    status: "active",
    scope: "delivery",
    startsAt: "2026-01-01T00:00:00.000Z",
    endsAt: null,
    rules: [
      {
        id: "rule-free-delivery-min",
        kind: "free_delivery",
        condition: "min_order_rub",
        operator: "gte",
        value: 5000,
        priority: 10,
        label: "Заказ от 5000 ₽",
      },
    ],
    bannerIds: ["banner-free-delivery"],
    couponIds: [],
    featuredProductIds: [],
    priority: 3,
    tags: ["free_delivery"],
    metadata: { zoneId: "base" },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "campaign-happy-hour",
    slug: "happy-hour",
    title: "Happy Hour",
    description: "Скидка в дневные часы",
    kind: "happy_hour",
    status: "active",
    scope: "order",
    startsAt: "2026-01-01T00:00:00.000Z",
    endsAt: null,
    rules: [PROMOTION_EXAMPLE_RULES[3]],
    bannerIds: [],
    couponIds: ["coupon-happy5"],
    featuredProductIds: [],
    priority: 7,
    tags: ["happy_hour"],
    metadata: { discountPercent: 5 },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "campaign-birthday",
    slug: "birthday-discount",
    title: "Birthday Discount",
    description: "Персональная скидка в месяц дня рождения",
    kind: "birthday_discount",
    status: "active",
    scope: "customer_segment",
    startsAt: "2026-01-01T00:00:00.000Z",
    endsAt: null,
    rules: [PROMOTION_EXAMPLE_RULES[2]],
    bannerIds: [],
    couponIds: ["coupon-birthday15"],
    featuredProductIds: [],
    priority: 12,
    tags: ["birthday"],
    metadata: { discountPercent: 15 },
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const PROMOTION_EXAMPLE_BANNERS: PromotionBanner[] = [
  {
    id: "banner-spring-hero",
    campaignId: "campaign-spring-bloom",
    title: "Весеннее цветение",
    subtitle: "Скидка 10% на весенние букеты",
    ctaLabel: "Смотреть коллекцию",
    ctaHref: "/catalog?season=spring",
    imageUrl: null,
    placement: "hero",
    rotationWeight: 10,
    status: "active",
    startsAt: "2026-03-01T00:00:00.000Z",
    endsAt: "2026-05-31T23:59:59.000Z",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "banner-flash-hero",
    campaignId: "campaign-flash-weekend",
    title: "Flash Weekend −15%",
    subtitle: "Только 48 часов",
    ctaLabel: "Успеть заказать",
    ctaHref: "/catalog?promo=flash",
    imageUrl: null,
    placement: "hero",
    rotationWeight: 20,
    status: "scheduled",
    startsAt: "2026-06-28T00:00:00.000Z",
    endsAt: "2026-06-29T23:59:59.000Z",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "banner-free-delivery",
    campaignId: "campaign-free-delivery-base",
    title: "Бесплатная доставка",
    subtitle: "При заказе от 5000 ₽ в базовой зоне",
    ctaLabel: null,
    ctaHref: null,
    imageUrl: null,
    placement: "catalog",
    rotationWeight: 5,
    status: "active",
    startsAt: "2026-01-01T00:00:00.000Z",
    endsAt: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const PROMOTION_EXAMPLE_COUPONS: PromotionCoupon[] = [
  {
    id: "coupon-spring10",
    code: "SPRING10",
    kind: "promo_code",
    discountType: "percent",
    discountValue: 10,
    minOrderRub: 3000,
    maxUses: 500,
    usedCount: 42,
    balanceRub: null,
    status: "active",
    validFrom: "2026-03-01T00:00:00.000Z",
    validUntil: "2026-05-31T23:59:59.000Z",
    campaignId: "campaign-spring-bloom",
    segmentRestrictions: [],
    productIds: [],
    categoryIds: ["bouquets"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "coupon-flash15",
    code: "FLASH15",
    kind: "coupon",
    discountType: "percent",
    discountValue: 15,
    minOrderRub: 2500,
    maxUses: 200,
    usedCount: 0,
    balanceRub: null,
    status: "scheduled",
    validFrom: "2026-06-28T00:00:00.000Z",
    validUntil: "2026-06-29T23:59:59.000Z",
    campaignId: "campaign-flash-weekend",
    segmentRestrictions: [],
    productIds: [],
    categoryIds: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "coupon-vip10",
    code: "VIP10",
    kind: "coupon",
    discountType: "percent",
    discountValue: 10,
    minOrderRub: null,
    maxUses: null,
    usedCount: 18,
    balanceRub: null,
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    campaignId: "campaign-vip-loyalty",
    segmentRestrictions: ["vip_customer"],
    productIds: [],
    categoryIds: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "coupon-happy5",
    code: "HAPPY5",
    kind: "promo_code",
    discountType: "percent",
    discountValue: 5,
    minOrderRub: 2000,
    maxUses: null,
    usedCount: 7,
    balanceRub: null,
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    campaignId: "campaign-happy-hour",
    segmentRestrictions: [],
    productIds: [],
    categoryIds: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "coupon-birthday15",
    code: "BDAY15",
    kind: "coupon",
    discountType: "percent",
    discountValue: 15,
    minOrderRub: null,
    maxUses: 1,
    usedCount: 0,
    balanceRub: null,
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    campaignId: "campaign-birthday",
    segmentRestrictions: [],
    productIds: [],
    categoryIds: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "gift-card-5000",
    code: "GIFT-5000-ABCD",
    kind: "gift_card",
    discountType: "fixed_rub",
    discountValue: 5000,
    minOrderRub: null,
    maxUses: 1,
    usedCount: 0,
    balanceRub: 5000,
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: "2027-01-01T00:00:00.000Z",
    campaignId: null,
    segmentRestrictions: [],
    productIds: [],
    categoryIds: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const PROMOTION_EXAMPLE_FEATURED: FeaturedProductPromotion[] = [
  {
    productId: "product-tulip-classic",
    campaignId: "campaign-spring-bloom",
    badge: "Seasonal",
    sortOrder: 1,
    highlightUntil: "2026-05-31T23:59:59.000Z",
  },
  {
    productId: "product-peony-premium",
    campaignId: "campaign-spring-bloom",
    badge: "Featured",
    sortOrder: 2,
    highlightUntil: "2026-05-31T23:59:59.000Z",
  },
];

export const PROMOTION_EXAMPLE_SCHEDULES: ScheduledPromotion[] = [
  {
    id: "schedule-flash-activate",
    campaignId: "campaign-flash-weekend",
    runAt: "2026-06-28T00:00:00.000Z",
    action: "activate",
    status: "pending",
    createdAt: NOW,
  },
  {
    id: "schedule-flash-deactivate",
    campaignId: "campaign-flash-weekend",
    runAt: "2026-06-29T23:59:59.000Z",
    action: "deactivate",
    status: "pending",
    createdAt: NOW,
  },
  {
    id: "schedule-banner-rotate",
    campaignId: "campaign-spring-bloom",
    runAt: "2026-06-26T08:00:00.000Z",
    action: "rotate_banner",
    status: "pending",
    createdAt: NOW,
  },
];

export const PROMOTION_EXAMPLE_AI_SUGGESTIONS: AiPromotionSuggestion[] = [
  {
    id: "ai-suggest-reactivation",
    title: "Reactivation campaign for inactive customers",
    rationale: "Сегмент inactive_customer может откликнуться на скидку 10% + free delivery",
    suggestedKind: "coupon",
    confidence: 0.72,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "ai-suggest-peony-flash",
    title: "Flash sale on peony bouquets",
    rationale: "Сезон пионов — повысить конверсию коротким flash sale",
    suggestedKind: "flash_sale",
    confidence: 0.81,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "ai-suggest-vip-early-access",
    title: "VIP early access to new collection",
    rationale: "VIP-клиенты с высоким LTV — эксклюзивный доступ без глубокой скидки",
    suggestedKind: "vip_discount",
    confidence: 0.65,
    status: "suggestion_only",
    createdAt: NOW,
  },
];

export const PROMOTION_EXAMPLE_LOYALTY: LoyaltyProgram = {
  id: "loyalty-bellaflore",
  name: "Bellaflore Loyalty",
  pointsPerRub: 1,
  tiers: [
    {
      id: "tier-bronze",
      name: "Bronze",
      minPoints: 0,
      discountPercent: 0,
      perks: ["Накопление баллов"],
    },
    {
      id: "tier-silver",
      name: "Silver",
      minPoints: 500,
      discountPercent: 5,
      perks: ["5% скидка", "Приоритетная доставка"],
    },
    {
      id: "tier-gold",
      name: "Gold",
      minPoints: 2000,
      discountPercent: 10,
      perks: ["10% скидка", "VIP-поддержка", "Подарок к дню рождения"],
    },
    {
      id: "tier-platinum",
      name: "Platinum",
      minPoints: 5000,
      discountPercent: 15,
      perks: ["15% скидка", "Эксклюзивные букеты", "Бесплатная доставка"],
    },
  ],
  status: "active",
  createdAt: NOW,
  updatedAt: NOW,
};

export function buildPromotionExampleRegistryState() {
  return {
    campaigns: [...PROMOTION_EXAMPLE_CAMPAIGNS],
    banners: [...PROMOTION_EXAMPLE_BANNERS],
    coupons: [...PROMOTION_EXAMPLE_COUPONS],
    featuredProducts: [...PROMOTION_EXAMPLE_FEATURED],
    schedules: [...PROMOTION_EXAMPLE_SCHEDULES],
    aiSuggestions: [...PROMOTION_EXAMPLE_AI_SUGGESTIONS],
    loyaltyProgram: { ...PROMOTION_EXAMPLE_LOYALTY },
  };
}
