// ==================================================
// SECTION: PRICING INTELLIGENCE
// РАЗДЕЛ: Public foundation exports
// ==================================================
export type {
  PricingRuleKind,
  PricingSeason,
  PricingRuleStatus,
  PricingDiscountType,
  PricingVipLevel,
  PricingAiPreparationStatus,
  PricingRule,
  PricingDiscountRule,
  PricingDeliveryRule,
  PricingZoneRate,
  PricingHistoryEntry,
  PricingMarginAnalysis,
  PricingSuggestion,
  PricingAiPreparation,
  PricingQuoteContext,
  PricingQuoteLine,
  PricingQuote,
  PricingStatistics,
  PricingIntelligenceSnapshot,
  PricingListFilters,
  PricingRegistryState,
  PricingReadOnlySummary,
} from "@/components/pricingIntelligence/pricingTypes";

export {
  PRICING_EXAMPLE_RULES,
  PRICING_EXAMPLE_DISCOUNTS,
  PRICING_EXAMPLE_DELIVERY_RULES,
  PRICING_EXAMPLE_ZONE_RATES,
  PRICING_EXAMPLE_HISTORY,
  PRICING_EXAMPLE_MARGINS,
  PRICING_EXAMPLE_SUGGESTIONS,
  PRICING_EXAMPLE_AI_PREPARATIONS,
  buildPricingExampleRegistryState,
} from "@/components/pricingIntelligence/pricingExamples";

export {
  PRICING_RULES_STORAGE_KEY,
  PRICING_ZONE_RATES_STORAGE_KEY,
  PRICING_DELIVERY_RULES_STORAGE_KEY,
  listPricingRules,
  getPricingRuleById,
  listActivePricingRules,
  listPricingRulesByKind,
  listDynamicPricingRules,
  listZonePricingRules,
  listHolidayPricingRules,
  listSeasonalPricingRules,
  listVipPricingRules,
  listZoneRates,
  getZoneRateById,
  listDeliveryPriceRules,
  getDeliveryPriceRuleByZone,
  resolveApplicablePricingRules,
  registerPricingRule,
  registerZoneRate,
  registerDeliveryPriceRule,
  seedPricingRulesRegistry,
  clearPricingRulesRegistry,
  resolveRuleStatus,
} from "@/components/pricingIntelligence/pricingRulesRegistry";

export {
  PRICING_DISCOUNT_STORAGE_KEY,
  PRICING_SUGGESTIONS_STORAGE_KEY,
  PRICING_AI_STORAGE_KEY,
  listDiscountRules,
  getDiscountRuleById,
  getDiscountRuleByCode,
  calculateDiscountAmount,
  listPriceSuggestions,
  getPriceSuggestionById,
  listPriceSuggestionsByProduct,
  listAiPricePreparations,
  getAiPricePreparationById,
  registerDiscountRule,
  registerPriceSuggestion,
  registerAiPricePreparation,
  seedPricingDiscountRegistry,
  clearPricingDiscountRegistry,
  resolveDiscountStatus,
} from "@/components/pricingIntelligence/pricingDiscountRegistry";

export {
  PRICING_HISTORY_STORAGE_KEY,
  PRICING_MARGINS_STORAGE_KEY,
  listPriceHistory,
  getLatestPriceForProduct,
  listMarginAnalysis,
  getMarginAnalysisByProduct,
  calculateAverageMarginPercent,
  countPriceChangesSince,
  registerPriceHistoryEntry,
  registerMarginAnalysis,
  seedPricingHistoryRegistry,
  clearPricingHistoryRegistry,
  getTopAdjustedProductId,
} from "@/components/pricingIntelligence/pricingHistoryRegistry";

export {
  PRICING_INTELLIGENCE_STORAGE_KEY,
  calculateDeliveryPrice,
  buildPricingQuote,
  calculatePricingStatistics,
  buildPricingIntelligenceSnapshot,
  initializePricingIntelligence,
  getPricingIntelligenceExample,
  getPricingReadOnlySummary,
  readPricingFoundationCapabilities,
  PRICING_INTELLIGENCE_ENGINE_SCHEMA,
  listAllPricingFoundationCapabilities,
} from "@/components/pricingIntelligence/pricingEngine";
