// ==================================================
// SECTION: PRICING INTELLIGENCE
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  PricingAiPreparation,
  PricingDeliveryRule,
  PricingDiscountRule,
  PricingHistoryEntry,
  PricingMarginAnalysis,
  PricingRule,
  PricingSuggestion,
  PricingZoneRate,
} from "@/components/pricingIntelligence/pricingTypes";

const NOW = new Date().toISOString();

export const PRICING_EXAMPLE_RULES: PricingRule[] = [
  {
    id: "rule-dynamic-weekend",
    kind: "dynamic",
    title: "Weekend Dynamic Pricing",
    description: "Небольшое повышение цен в выходные",
    priority: 10,
    status: "active",
    productIds: [],
    categoryIds: ["cat-bouquets"],
    zoneIds: [],
    vipLevels: [],
    seasons: [],
    holidayDates: [],
    adjustmentPercent: 5,
    adjustmentRub: 0,
    minOrderRub: null,
    maxDiscountRub: null,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: { dayType: "weekend" },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-zone-base",
    kind: "zone",
    title: "Base Zone Pricing",
    description: "Базовая зона без наценки",
    priority: 5,
    status: "active",
    productIds: [],
    categoryIds: [],
    zoneIds: ["base"],
    vipLevels: [],
    seasons: [],
    holidayDates: [],
    adjustmentPercent: 0,
    adjustmentRub: 0,
    minOrderRub: null,
    maxDiscountRub: null,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: {},
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-zone-7km",
    kind: "zone",
    title: "7km Zone Pricing",
    description: "Наценка для зоны 7 км",
    priority: 6,
    status: "active",
    productIds: [],
    categoryIds: [],
    zoneIds: ["7km"],
    vipLevels: [],
    seasons: [],
    holidayDates: [],
    adjustmentPercent: 0,
    adjustmentRub: 300,
    minOrderRub: null,
    maxDiscountRub: null,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: {},
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-holiday-march8",
    kind: "holiday",
    title: "8 March Holiday Pricing",
    description: "Праздничная наценка 8 марта",
    priority: 20,
    status: "active",
    productIds: [],
    categoryIds: ["cat-bouquets", "cat-premium"],
    zoneIds: [],
    vipLevels: [],
    seasons: ["spring"],
    holidayDates: ["03-08"],
    adjustmentPercent: 15,
    adjustmentRub: 0,
    minOrderRub: null,
    maxDiscountRub: null,
    validFrom: "2026-03-01T00:00:00.000Z",
    validUntil: "2026-03-09T23:59:59.000Z",
    metadata: { holiday: "march_8" },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-seasonal-spring",
    kind: "seasonal",
    title: "Spring Seasonal Pricing",
    description: "Сезонная наценка на весенние цветы",
    priority: 12,
    status: "active",
    productIds: ["product-tulip-classic", "product-peony-premium"],
    categoryIds: ["cat-seasonal"],
    zoneIds: [],
    vipLevels: [],
    seasons: ["spring"],
    holidayDates: [],
    adjustmentPercent: 8,
    adjustmentRub: 0,
    minOrderRub: null,
    maxDiscountRub: null,
    validFrom: "2026-03-01T00:00:00.000Z",
    validUntil: "2026-05-31T23:59:59.000Z",
    metadata: { season: "spring" },
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-vip-discount",
    kind: "vip",
    title: "VIP Pricing",
    description: "Скидка для VIP-клиентов",
    priority: 15,
    status: "active",
    productIds: [],
    categoryIds: [],
    zoneIds: [],
    vipLevels: [2, 3],
    seasons: [],
    holidayDates: [],
    adjustmentPercent: -10,
    adjustmentRub: 0,
    minOrderRub: null,
    maxDiscountRub: 2000,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    metadata: {},
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const PRICING_EXAMPLE_DISCOUNTS: PricingDiscountRule[] = [
  {
    id: "discount-first-order",
    code: "FIRST10",
    title: "First Order Discount",
    discountType: "percent",
    discountValue: 10,
    minOrderRub: 3000,
    maxUses: null,
    usedCount: 45,
    status: "active",
    stackable: false,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "discount-bundle",
    code: null,
    title: "Bundle Discount",
    discountType: "fixed_rub",
    discountValue: 500,
    minOrderRub: 8000,
    maxUses: null,
    usedCount: 12,
    status: "active",
    stackable: true,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const PRICING_EXAMPLE_DELIVERY_RULES: PricingDeliveryRule[] = [
  {
    id: "delivery-base",
    zoneId: "base",
    zoneLabel: "Базовая зона",
    baseDeliveryRub: 0,
    freeDeliveryFromRub: 5000,
    surgeMultiplier: 1,
    holidaySurchargeRub: 0,
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "delivery-7km",
    zoneId: "7km",
    zoneLabel: "До 7 км",
    baseDeliveryRub: 490,
    freeDeliveryFromRub: 7000,
    surgeMultiplier: 1.1,
    holidaySurchargeRub: 200,
    status: "active",
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "delivery-holiday",
    zoneId: "base",
    zoneLabel: "Holiday Surcharge Base",
    baseDeliveryRub: 0,
    freeDeliveryFromRub: null,
    surgeMultiplier: 1.25,
    holidaySurchargeRub: 350,
    status: "active",
    validFrom: "2026-03-07T00:00:00.000Z",
    validUntil: "2026-03-09T23:59:59.000Z",
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const PRICING_EXAMPLE_ZONE_RATES: PricingZoneRate[] = [
  {
    id: "zone-rate-base",
    zoneId: "base",
    zoneLabel: "Базовая зона",
    multiplier: 1,
    flatAdjustmentRub: 0,
    isActive: true,
    updatedAt: NOW,
  },
  {
    id: "zone-rate-7km",
    zoneId: "7km",
    zoneLabel: "До 7 км",
    multiplier: 1.05,
    flatAdjustmentRub: 300,
    isActive: true,
    updatedAt: NOW,
  },
  {
    id: "zone-rate-15km",
    zoneId: "15km",
    zoneLabel: "До 15 км",
    multiplier: 1.12,
    flatAdjustmentRub: 600,
    isActive: true,
    updatedAt: NOW,
  },
];

export const PRICING_EXAMPLE_HISTORY: PricingHistoryEntry[] = [
  {
    id: "history-rose-up",
    productId: "product-rose-classic",
    previousPriceRub: 4200,
    newPriceRub: 4500,
    changeReason: "Seasonal adjustment",
    ruleId: "rule-seasonal-spring",
    changedAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "history-peony-up",
    productId: "product-peony-premium",
    previousPriceRub: 6800,
    newPriceRub: 7200,
    changeReason: "Spring demand",
    ruleId: "rule-seasonal-spring",
    changedAt: "2026-03-15T10:00:00.000Z",
  },
  {
    id: "history-tulip-down",
    productId: "product-tulip-classic",
    previousPriceRub: 4000,
    newPriceRub: 3800,
    changeReason: "Promotional adjustment",
    ruleId: null,
    changedAt: "2026-04-01T08:00:00.000Z",
  },
];

export const PRICING_EXAMPLE_MARGINS: PricingMarginAnalysis[] = [
  {
    productId: "product-rose-classic",
    basePriceRub: 4500,
    costRub: 2700,
    marginRub: 1800,
    marginPercent: 40,
    suggestedPriceRub: 4600,
    calculatedAt: NOW,
  },
  {
    productId: "product-peony-premium",
    basePriceRub: 7200,
    costRub: 4320,
    marginRub: 2880,
    marginPercent: 40,
    suggestedPriceRub: 7500,
    calculatedAt: NOW,
  },
  {
    productId: "product-tulip-classic",
    basePriceRub: 3800,
    costRub: 2470,
    marginRub: 1330,
    marginPercent: 35,
    suggestedPriceRub: 3900,
    calculatedAt: NOW,
  },
];

export const PRICING_EXAMPLE_SUGGESTIONS: PricingSuggestion[] = [
  {
    id: "suggest-peony-up",
    productId: "product-peony-premium",
    title: "Increase peony premium price",
    currentPriceRub: 7200,
    suggestedPriceRub: 7500,
    rationale: "Высокий seasonal demand и margin ниже целевого",
    confidence: 0.81,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "suggest-rose-hold",
    productId: "product-rose-classic",
    title: "Hold rose classic price",
    currentPriceRub: 4500,
    suggestedPriceRub: 4500,
    rationale: "Стабильный спрос, margin в норме",
    confidence: 0.74,
    status: "suggestion_only",
    createdAt: NOW,
  },
];

export const PRICING_EXAMPLE_AI_PREPARATIONS: PricingAiPreparation[] = [
  {
    id: "ai-prep-holiday-surge",
    title: "Holiday surge pricing",
    rationale: "Подготовить holiday pricing rule для 8 марта на premium категорию",
    targetKind: "holiday",
    suggestedAdjustmentPercent: 12,
    confidence: 0.86,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "ai-prep-vip-tier",
    title: "VIP tier pricing review",
    rationale: "VIP level 3 может получить фиксированную скидку без stack с seasonal",
    targetKind: "vip",
    suggestedAdjustmentPercent: -8,
    confidence: 0.67,
    status: "suggestion_only",
    createdAt: NOW,
  },
];

export function buildPricingExampleRegistryState() {
  return {
    rules: [...PRICING_EXAMPLE_RULES],
    discounts: [...PRICING_EXAMPLE_DISCOUNTS],
    deliveryRules: [...PRICING_EXAMPLE_DELIVERY_RULES],
    zoneRates: [...PRICING_EXAMPLE_ZONE_RATES],
    history: [...PRICING_EXAMPLE_HISTORY],
    margins: [...PRICING_EXAMPLE_MARGINS],
    suggestions: [...PRICING_EXAMPLE_SUGGESTIONS],
    aiPreparations: [...PRICING_EXAMPLE_AI_PREPARATIONS],
  };
}
