// ==================================================
// SECTION: PRODUCTION READINESS
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  ChecklistItem,
  FutureLaunchReport,
  ProductionRiskFactor,
  RollbackPlan,
} from "@/components/productionReadiness/productionTypes";

const NOW = new Date().toISOString();

export const PRODUCTION_EXAMPLE_CHECKLISTS: ChecklistItem[] = [
  // Launch
  {
    id: "launch-001",
    category: "launch",
    title: "Foundation modules complete",
    description: "All intelligence foundation stages (29–40) registered",
    status: "passed",
    priority: "critical",
    owner: "platform",
    notes: "Stage 40 — Production Readiness",
    completedAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "launch-002",
    category: "launch",
    title: "Go/No-Go assessment defined",
    description: "Launch decision framework registered in foundation",
    status: "passed",
    priority: "critical",
    owner: "platform",
    notes: null,
    completedAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "launch-003",
    category: "launch",
    title: "Production wiring complete",
    description: "All bridges wired to live systems",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: "Future wiring phase",
    completedAt: null,
    updatedAt: NOW,
  },
  // Environment
  {
    id: "env-001",
    category: "environment",
    title: "Production env vars documented",
    description: "All required secrets and env keys listed",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "env-002",
    category: "environment",
    title: "Staging environment mirrors production",
    description: "Staging config matches prod topology",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Deployment
  {
    id: "deploy-001",
    category: "deployment",
    title: "CI/CD pipeline configured",
    description: "Automated build, test, deploy pipeline ready",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "deploy-002",
    category: "deployment",
    title: "Rollback plan tested",
    description: "Rollback steps verified in staging",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Backup
  {
    id: "backup-001",
    category: "backup",
    title: "Database backup schedule",
    description: "Daily automated backups configured",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "backup-002",
    category: "backup",
    title: "Backup restore tested",
    description: "Restore procedure verified within RTO target",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Security
  {
    id: "security-001",
    category: "security",
    title: "Admin auth hardened",
    description: "Session, CSRF, rate limiting verified",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "security-002",
    category: "security",
    title: "Secrets not in repository",
    description: "No credentials committed to git",
    status: "passed",
    priority: "critical",
    owner: "platform",
    notes: "Foundation uses localStorage seeds only",
    completedAt: NOW,
    updatedAt: NOW,
  },
  // Monitoring
  {
    id: "monitor-001",
    category: "monitoring",
    title: "Error tracking configured",
    description: "Sentry or equivalent connected",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "monitor-002",
    category: "monitoring",
    title: "Uptime monitoring active",
    description: "Health endpoints monitored externally",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Performance
  {
    id: "perf-001",
    category: "performance",
    title: "Core Web Vitals baseline",
    description: "LCP, FID, CLS measured on key pages",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "perf-002",
    category: "performance",
    title: "Image optimization verified",
    description: "Product images use next/image or equivalent",
    status: "pending",
    priority: "medium",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // SEO
  {
    id: "seo-001",
    category: "seo",
    title: "Sitemap and robots.txt",
    description: "Search engine crawl configuration active",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "seo-002",
    category: "seo",
    title: "Meta tags and Open Graph",
    description: "All public pages have correct meta",
    status: "pending",
    priority: "medium",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Telegram
  {
    id: "telegram-001",
    category: "telegram",
    title: "Bot token configured",
    description: "TELEGRAM_BOT_TOKEN set in production env",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "telegram-002",
    category: "telegram",
    title: "Webhook endpoint secured",
    description: "Telegram webhook validates secret token",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Payment
  {
    id: "payment-001",
    category: "payment",
    title: "Payment provider live keys",
    description: "Production payment credentials configured",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "payment-002",
    category: "payment",
    title: "Payment webhook verified",
    description: "Webhook signature validation tested",
    status: "pending",
    priority: "critical",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  // Admin
  {
    id: "admin-001",
    category: "admin",
    title: "Admin dashboard accessible",
    description: "Admin routes protected and functional",
    status: "pending",
    priority: "high",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
  {
    id: "admin-002",
    category: "admin",
    title: "Admin audit logging",
    description: "Critical admin actions logged",
    status: "pending",
    priority: "medium",
    owner: null,
    notes: null,
    completedAt: null,
    updatedAt: NOW,
  },
];

export const PRODUCTION_EXAMPLE_ROLLBACK_PLAN: RollbackPlan = {
  id: "rollback-plan-v1",
  title: "Bellaflore Production Rollback Plan",
  description: "Standard rollback procedure for failed deployment",
  triggerConditions: [
    "Critical checkout failure rate > 5%",
    "Payment webhook errors sustained > 10 min",
    "Database migration failure",
    "Security incident detected",
  ],
  steps: [
    {
      id: "rollback-step-1",
      order: 1,
      title: "Halt deployment pipeline",
      description: "Stop CI/CD and prevent further releases",
      estimatedMinutes: 2,
      status: "ready",
      responsibleRole: "devops",
    },
    {
      id: "rollback-step-2",
      order: 2,
      title: "Revert to previous deployment",
      description: "Deploy last known good build artifact",
      estimatedMinutes: 10,
      status: "pending",
      responsibleRole: "devops",
    },
    {
      id: "rollback-step-3",
      order: 3,
      title: "Verify health endpoints",
      description: "Confirm /api/health and core routes respond",
      estimatedMinutes: 5,
      status: "pending",
      responsibleRole: "platform",
    },
    {
      id: "rollback-step-4",
      order: 4,
      title: "Notify stakeholders",
      description: "Alert team via Telegram and status page",
      estimatedMinutes: 3,
      status: "ready",
      responsibleRole: "ops",
    },
  ],
  lastTestedAt: null,
  updatedAt: NOW,
};

export const PRODUCTION_EXAMPLE_RISK_FACTORS: ProductionRiskFactor[] = [
  {
    id: "risk-wiring",
    label: "Foundation not wired",
    description: "Intelligence modules exist but are not connected to live systems",
    weight: 25,
    score: 20,
    level: "elevated",
    category: "general",
  },
  {
    id: "risk-payment",
    label: "Payment not production-ready",
    description: "Payment checklist items pending",
    weight: 20,
    score: 18,
    level: "high",
    category: "payment",
  },
  {
    id: "risk-telegram",
    label: "Telegram not configured",
    description: "Telegram bot and webhook pending",
    weight: 15,
    score: 14,
    level: "elevated",
    category: "telegram",
  },
  {
    id: "risk-backup",
    label: "Backup untested",
    description: "Backup and restore procedures not verified",
    weight: 15,
    score: 12,
    level: "moderate",
    category: "backup",
  },
  {
    id: "risk-foundation",
    label: "Architecture foundation complete",
    description: "All 12 foundation stages registered — positive factor",
    weight: 10,
    score: 2,
    level: "low",
    category: "launch",
  },
];

export const PRODUCTION_EXAMPLE_LAUNCH_REPORT: FutureLaunchReport = {
  id: "launch-report-foundation-ch1",
  title: "Bellaflore Architecture Foundation — Chapter 1 Report",
  status: "draft",
  summary:
    "Foundation chapter complete (Stages 29–40). All intelligence modules registered in isolated read-only mode. Wiring, UI, and live launch remain future phases.",
  sections: [
    "Customer, Promotion, Loyalty Intelligence",
    "Catalog, Search, Pricing, Recommendation Intelligence",
    "CRM, Supplier, Finance Intelligence",
    "Integration Intelligence",
    "Production Readiness Foundation",
  ],
  targetLaunchDate: null,
  generatedAt: NOW,
};

export function buildProductionExampleRegistryState() {
  return {
    checklists: [...PRODUCTION_EXAMPLE_CHECKLISTS],
    rollbackPlan: { ...PRODUCTION_EXAMPLE_ROLLBACK_PLAN },
    riskFactors: [...PRODUCTION_EXAMPLE_RISK_FACTORS],
    futureLaunchReport: { ...PRODUCTION_EXAMPLE_LAUNCH_REPORT },
  };
}
