// ==================================================
// SECTION: PRODUCT STORAGE
// РАЗДЕЛ: Seed products (no DB)
// ==================================================
import type { StoredProduct } from "@/components/productStorage/productStorageTypes";

const BASE_TIME = "2026-06-20T10:00:00.000Z";

export const PRODUCT_STORAGE_SEED_PRODUCTS: StoredProduct[] = [
  {
    id: "product-white-roses-101",
    slug: "belye-rozy-101",
    sku: "BF-ROSE-101-WHT",
    title: "Белые розы 101",
    shortDescription: "Классический монобукет из белых роз для особого случая.",
    description:
      "Премиальный букет из 101 белой розы для торжественного подарка. Композиция собирается вручную флористами Bellaflore.",
    category: "Розы",
    tags: ["розы", "премиум", "монобукет"],
    price: 18900,
    comparePrice: 21900,
    status: "draft",
    stock: 12,
    images: [
      {
        id: "photo-seed-01",
        photoNumber: 1,
        fileName: "white-roses-101.jpg",
        fileSizeBytes: 860160,
        fileSizeLabel: "840 KB",
        fileFormat: "JPEG",
        isMain: true,
        placeholderLabel: "placeholder · белые розы",
        seo: {
          imageTitle: "Белые розы 101",
          imageAlt: "Белые розы 101 с доставкой по Москве — Bellaflore",
          imageCaption: "Премиальный букет из 101 белой розы с доставкой по Москве.",
          imageDescription:
            "Авторский букет Bellaflore для подарка, свадьбы или премиального события.",
          seoFilename: "belye-rozy-101-dostavka-moskva-bellaflore.jpg",
          canonicalImageUrl: "https://bellaflore.ru/media/catalog/belye-rozy-101.jpg",
          openGraphImage: "https://bellaflore.ru/og/belye-rozy-101.jpg",
          twitterImage: "https://bellaflore.ru/twitter/belye-rozy-101.jpg",
          imageKeywords: "белые розы, 101 роза, доставка цветов Москва",
          localSeoPhrase: "доставка цветов Москва",
        },
        uploadedAt: BASE_TIME,
      },
    ],
    seo: {
      title: "Белые розы 101 — купить букет с доставкой по Москве | Bellaflore",
      metaDescription:
        "Закажите букет из 101 белой розы с премиальной доставкой по Москве. Bellaflore — доставка цветов Москва.",
      keywords: "белые розы 101, букет роз, доставка цветов Москва",
      h1: "Белые розы 101",
      h2: "Премиальный букет с доставкой по Москве",
      imageAltText: "Букет из 101 белой розы Bellaflore",
      canonicalUrl: "https://bellaflore.ru/catalog/belye-rozy-101",
      openGraphTitle: "Белые розы 101 — Bellaflore",
      openGraphDescription: "Премиальный букет из 101 белой розы с доставкой по Москве.",
      structuredDataType: "Product",
      localSeoPhrase: "доставка цветов Москва",
      searchIntent: "buy",
    },
    flowerCount: 101,
    size: "L",
    composition: "101 белая роза, упаковка premium",
    colorPalette: "Белый, кремовый",
    occasion: "premium",
    seasonality: "Круглый год",
    deliveryNote: "Доставка по Москве в день заказа",
    createdAt: BASE_TIME,
    updatedAt: "2026-06-25T12:00:00.000Z",
  },
  {
    id: "product-pink-peonies",
    slug: "rozovye-piony",
    sku: "BF-PEONY-PNK",
    title: "Розовые пионы",
    shortDescription: "Нежный сезонный букет с пышными розовыми пионами.",
    description: "Нежный сезонный букет с пышными розовыми пионами для особого настроения.",
    category: "Пионы",
    tags: ["пионы", "seasonal"],
    price: 12400,
    comparePrice: null,
    status: "published",
    stock: 8,
    images: [
      {
        id: "photo-seed-02",
        photoNumber: 1,
        fileName: "pink-peonies.jpg",
        fileSizeBytes: 737280,
        fileSizeLabel: "720 KB",
        fileFormat: "JPEG",
        isMain: true,
        placeholderLabel: "placeholder · розовые пионы",
        seo: {
          imageTitle: "Розовые пионы",
          imageAlt: "Розовые пионы с доставкой по Москве — Bellaflore",
          imageCaption: "Нежный букет из розовых пионов.",
          imageDescription: "Сезонный букет Bellaflore с доставкой по Москве.",
          seoFilename: "rozovye-piony-dostavka-moskva.jpg",
          canonicalImageUrl: "https://bellaflore.ru/media/catalog/rozovye-piony.jpg",
          openGraphImage: "https://bellaflore.ru/og/rozovye-piony.jpg",
          twitterImage: "https://bellaflore.ru/twitter/rozovye-piony.jpg",
          imageKeywords: "пионы, розовые пионы, доставка цветов Москва",
          localSeoPhrase: "доставка цветов Москва",
        },
        uploadedAt: "2026-06-21T09:00:00.000Z",
      },
    ],
    seo: {
      title: "Розовые пионы — купить букет | Bellaflore",
      metaDescription: "Букет розовых пионов с доставкой по Москве от Bellaflore.",
      keywords: "розовые пионы, букет пионов",
      h1: "Розовые пионы",
      h2: "Сезонный букет Bellaflore",
      imageAltText: "Букет розовых пионов Bellaflore",
      canonicalUrl: "https://bellaflore.ru/catalog/rozovye-piony",
      openGraphTitle: "Розовые пионы — Bellaflore",
      openGraphDescription: "Нежный букет розовых пионов с доставкой.",
      structuredDataType: "Product",
      localSeoPhrase: "доставка цветов Москва",
      searchIntent: "gift",
    },
    flowerCount: 25,
    size: "M",
    composition: "25 розовых пионов",
    colorPalette: "Розовый",
    occasion: "love",
    seasonality: "Май–Июль",
    deliveryNote: "Сезонный товар",
    createdAt: "2026-06-18T08:00:00.000Z",
    updatedAt: "2026-06-24T16:00:00.000Z",
  },
  {
    id: "product-red-roses-51",
    slug: "krasnye-rozy-51",
    sku: "BF-ROSE-51-RED",
    title: "Красные розы 51",
    shortDescription: "Выразительный букет из красных роз.",
    description: "Выразительный букет из красных роз для романтического жеста.",
    category: "Розы",
    tags: ["розы", "love"],
    price: 11200,
    comparePrice: 12900,
    status: "hidden",
    stock: 5,
    images: [],
    seo: {
      title: "Красные розы 51 — Bellaflore",
      metaDescription: "Букет из 51 красной розы с доставкой по Москве.",
      keywords: "красные розы, 51 роза",
      h1: "Красные розы 51",
      h2: "Романтический букет",
      imageAltText: "",
      canonicalUrl: "https://bellaflore.ru/catalog/krasnye-rozy-51",
      openGraphTitle: "Красные розы 51",
      openGraphDescription: "Букет красных роз с доставкой.",
      structuredDataType: "Product",
      localSeoPhrase: "доставка цветов Москва",
      searchIntent: "buy",
    },
    flowerCount: 51,
    size: "M",
    composition: "51 красная роза",
    colorPalette: "Красный",
    occasion: "love",
    seasonality: "Круглый год",
    deliveryNote: "",
    createdAt: "2026-06-15T12:00:00.000Z",
    updatedAt: "2026-06-22T11:00:00.000Z",
  },
];

export const PRODUCT_STORAGE_CATEGORIES = ["all", "Розы", "Пионы", "Авторские", "Корзины"];
