// ==================================================
// SECTION: FINANCE INTELLIGENCE
// РАЗДЕЛ: Public foundation exports
// ==================================================
export type {
  RevenueKind,
  ExpenseKind,
  RefundStatus,
  CashFlowDirection,
  FinanceAiPreparationStatus,
  RevenueEntry,
  ExpenseEntry,
  RefundEntry,
  CashFlowEntry,
  DailyRevenueMetric,
  MonthlyRevenueMetric,
  MarginAnalyticsEntry,
  CourierCostEntry,
  SupplierCostEntry,
  OperationalExpenseSummary,
  ProfitSummary,
  RefundStatistics,
  FinancialDashboardSnapshot,
  FinancialForecast,
  FinanceAiPreparation,
  FinanceStatistics,
  FinanceIntelligenceSnapshot,
  RevenueListFilters,
  ExpenseListFilters,
  FinanceRegistryState,
  FinanceReadOnlySummary,
} from "@/components/financeIntelligence/financeTypes";

export {
  FINANCE_EXAMPLE_REVENUE,
  FINANCE_EXAMPLE_EXPENSES,
  FINANCE_EXAMPLE_REFUNDS,
  FINANCE_EXAMPLE_CASH_FLOW,
  FINANCE_EXAMPLE_DAILY_REVENUE,
  FINANCE_EXAMPLE_MONTHLY_REVENUE,
  FINANCE_EXAMPLE_MARGIN_ANALYTICS,
  FINANCE_EXAMPLE_COURIER_COSTS,
  FINANCE_EXAMPLE_SUPPLIER_COSTS,
  FINANCE_EXAMPLE_OPERATIONAL,
  FINANCE_EXAMPLE_FORECASTS,
  FINANCE_EXAMPLE_AI,
  buildFinanceExampleRegistryState,
} from "@/components/financeIntelligence/financeExamples";

export {
  FINANCE_REVENUE_STORAGE_KEY,
  FINANCE_DAILY_REVENUE_STORAGE_KEY,
  FINANCE_MONTHLY_REVENUE_STORAGE_KEY,
  listRevenueEntries,
  getRevenueById,
  getRevenueByOrderId,
  listRevenueByKind,
  calculateTotalRevenue,
  listDailyRevenue,
  getDailyRevenueByDate,
  listMonthlyRevenue,
  getMonthlyRevenueByMonth,
  registerRevenueEntry,
  seedRevenueRegistry,
  clearRevenueRegistry,
} from "@/components/financeIntelligence/revenueRegistry";

export {
  FINANCE_EXPENSE_STORAGE_KEY,
  FINANCE_REFUND_STORAGE_KEY,
  FINANCE_CASH_FLOW_STORAGE_KEY,
  FINANCE_COURIER_COST_STORAGE_KEY,
  FINANCE_SUPPLIER_COST_STORAGE_KEY,
  FINANCE_OPERATIONAL_STORAGE_KEY,
  listExpenseEntries,
  getExpenseById,
  listExpensesByKind,
  calculateTotalExpenses,
  listCourierCosts,
  listSupplierCosts,
  listOperationalExpenses,
  listRefunds,
  getRefundById,
  listCashFlow,
  calculateCashFlowBalance,
  registerExpenseEntry,
  registerRefundEntry,
  registerCashFlowEntry,
  seedExpenseRegistry,
  clearExpenseRegistry,
} from "@/components/financeIntelligence/expenseRegistry";

export {
  calculateMarginPercent,
  calculateMarginRub,
  buildMarginAnalyticsEntry,
  calculateProfitSummary,
  calculateAverageMarginPercent,
  findLowestMarginProduct,
  findHighestMarginProduct,
  compareProfitPeriods,
} from "@/components/financeIntelligence/profitEngine";

export {
  FINANCE_FORECAST_STORAGE_KEY,
  FINANCE_AI_STORAGE_KEY,
  calculateRefundStatistics,
  calculateFinanceStatistics,
  buildFinancialDashboardSnapshot,
  listFinancialForecasts,
  getFinancialForecastById,
  listAiFinancePreparations,
  getAiFinancePreparationById,
  registerFinancialForecast,
  registerAiFinancePreparation,
  seedFinanceMetricsRegistry,
  clearFinanceMetricsRegistry,
  buildMarginAnalyticsSummary,
  buildCashFlowSummary,
} from "@/components/financeIntelligence/financeMetrics";

export {
  FINANCE_INTELLIGENCE_STORAGE_KEY,
  buildFinanceIntelligenceSnapshot,
  initializeFinanceIntelligence,
  getFinanceIntelligenceExample,
  getFinanceReadOnlySummary,
  readFinanceFoundationCapabilities,
  FINANCE_INTELLIGENCE_ENGINE_SCHEMA,
  listAllFinanceFoundationCapabilities,
} from "@/components/financeIntelligence/financeEngine";
