// ==================================================
// SECTION: NOTIFICATION INTELLIGENCE
// РАЗДЕЛ: Default rules catalog
// ==================================================
import type { NotificationRule } from "@/components/notificationIntelligence/notificationIntelligenceTypes";

export const DEFAULT_NOTIFICATION_RULES: NotificationRule[] = [
  {
    id: "rule-new-order",
    eventKind: "new_order",
    enabled: true,
    channels: ["telegram", "in_app", "admin_sound"],
    recipientRole: "admin",
    priority: "high",
    repeatAfterMinutes: [3, 10],
    escalateAfterMinutes: 10,
    escalateToPriority: "critical",
    escalateToChannels: ["telegram", "in_app", "admin_sound", "email"],
    suppressIfSent: false,
  },
  {
    id: "rule-order-confirmed",
    eventKind: "order_confirmed",
    enabled: true,
    channels: ["in_app", "telegram"],
    recipientRole: "admin",
    priority: "normal",
    repeatAfterMinutes: [],
    escalateAfterMinutes: null,
    escalateToPriority: null,
    escalateToChannels: [],
    suppressIfSent: true,
  },
  {
    id: "rule-courier-assigned",
    eventKind: "order_courier_assigned",
    enabled: true,
    channels: ["in_app", "telegram"],
    recipientRole: "admin",
    priority: "normal",
    repeatAfterMinutes: [],
    escalateAfterMinutes: null,
    escalateToPriority: null,
    escalateToChannels: [],
    suppressIfSent: true,
  },
  {
    id: "rule-order-in-delivery",
    eventKind: "order_in_delivery",
    enabled: true,
    channels: ["in_app"],
    recipientRole: "customer",
    priority: "normal",
    repeatAfterMinutes: [],
    escalateAfterMinutes: null,
    escalateToPriority: null,
    escalateToChannels: [],
    suppressIfSent: true,
  },
  {
    id: "rule-order-delivered",
    eventKind: "order_delivered",
    enabled: true,
    channels: ["in_app", "telegram"],
    recipientRole: "admin",
    priority: "low",
    repeatAfterMinutes: [],
    escalateAfterMinutes: null,
    escalateToPriority: null,
    escalateToChannels: [],
    suppressIfSent: true,
  },
  {
    id: "rule-low-stock",
    eventKind: "low_stock",
    enabled: true,
    channels: ["in_app", "email"],
    recipientRole: "admin",
    priority: "high",
    repeatAfterMinutes: [30],
    escalateAfterMinutes: 60,
    escalateToPriority: "critical",
    escalateToChannels: ["in_app", "email", "telegram"],
    suppressIfSent: false,
  },
  {
    id: "rule-telegram-failed",
    eventKind: "telegram_failed",
    enabled: true,
    channels: ["in_app", "admin_sound", "email"],
    recipientRole: "admin",
    priority: "critical",
    repeatAfterMinutes: [2],
    escalateAfterMinutes: 5,
    escalateToPriority: "critical",
    escalateToChannels: ["in_app", "admin_sound", "email"],
    suppressIfSent: false,
  },
  {
    id: "rule-order-not-confirmed",
    eventKind: "order_not_confirmed",
    enabled: true,
    channels: ["in_app", "admin_sound"],
    recipientRole: "admin",
    priority: "high",
    repeatAfterMinutes: [3, 10],
    escalateAfterMinutes: 10,
    escalateToPriority: "critical",
    escalateToChannels: ["in_app", "admin_sound", "telegram"],
    suppressIfSent: false,
  },
  {
    id: "rule-delivery-delay",
    eventKind: "delivery_delay",
    enabled: true,
    channels: ["in_app", "telegram"],
    recipientRole: "admin",
    priority: "high",
    repeatAfterMinutes: [5],
    escalateAfterMinutes: 15,
    escalateToPriority: "critical",
    escalateToChannels: ["in_app", "telegram", "admin_sound"],
    suppressIfSent: false,
  },
];

export function getDefaultNotificationRules(): NotificationRule[] {
  return DEFAULT_NOTIFICATION_RULES.map((rule) => ({
    ...rule,
    channels: [...rule.channels],
    repeatAfterMinutes: [...rule.repeatAfterMinutes],
    escalateToChannels: [...rule.escalateToChannels],
  }));
}
