// ==================================================
// SECTION: SUPPLIER INTELLIGENCE
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  Supplier,
  SupplierAiPreparation,
  SupplierAnalyticsMetric,
  SupplierContract,
  SupplierDeliverySchedule,
  SupplierHistoryEntry,
  SupplierPriceEntry,
  SupplierStockEntry,
} from "@/components/supplierIntelligence/supplierTypes";

const NOW = new Date().toISOString();

export const SUPPLIER_EXAMPLE_SUPPLIERS: Supplier[] = [
  {
    id: "supplier-flora-moscow",
    name: "Flora Moscow",
    code: "FLORA-MSK",
    contactName: "Алексей Петров",
    contactPhone: "+7 495 111-22-33",
    contactEmail: "sales@floramoscow.example",
    categories: ["flowers", "greenery"],
    rating: 4.8,
    reliabilityScore: 92,
    reliabilityLevel: "excellent",
    isPreferred: true,
    isBackup: false,
    status: "active",
    deliveryTimeDays: 1,
    minOrderRub: 5000,
    notes: ["Основной поставщик роз и пионов"],
    createdAt: "2024-01-15T00:00:00.000Z",
    updatedAt: NOW,
  },
  {
    id: "supplier-bloom-trade",
    name: "Bloom Trade",
    code: "BLOOM-TR",
    contactName: "Марина Соколова",
    contactPhone: "+7 495 444-55-66",
    contactEmail: "orders@bloomtrade.example",
    categories: ["flowers", "packaging", "add_ons"],
    rating: 4.3,
    reliabilityScore: 78,
    reliabilityLevel: "good",
    isPreferred: false,
    isBackup: true,
    status: "active",
    deliveryTimeDays: 2,
    minOrderRub: 3000,
    notes: ["Backup для сезонных позиций"],
    createdAt: "2024-06-01T00:00:00.000Z",
    updatedAt: NOW,
  },
  {
    id: "supplier-green-pack",
    name: "Green & Pack",
    code: "GRNPCK",
    contactName: "Игорь Волков",
    contactPhone: "+7 495 777-88-99",
    contactEmail: null,
    categories: ["greenery", "packaging", "consumables"],
    rating: 4.0,
    reliabilityScore: 65,
    reliabilityLevel: "fair",
    isPreferred: false,
    isBackup: false,
    status: "active",
    deliveryTimeDays: 3,
    minOrderRub: 2000,
    notes: [],
    createdAt: "2025-02-10T00:00:00.000Z",
    updatedAt: NOW,
  },
];

export const SUPPLIER_EXAMPLE_PRICES: SupplierPriceEntry[] = [
  {
    id: "price-flora-rose-red",
    supplierId: "supplier-flora-moscow",
    productSku: "flower-rose-red-60",
    productTitle: "Роза красная 60 см",
    unit: "шт",
    purchasePriceRub: 85,
    minQuantity: 25,
    validFrom: "2026-01-01T00:00:00.000Z",
    validUntil: null,
    updatedAt: NOW,
  },
  {
    id: "price-flora-peony",
    supplierId: "supplier-flora-moscow",
    productSku: "flower-peony-pink",
    productTitle: "Пион розовый",
    unit: "шт",
    purchasePriceRub: 220,
    minQuantity: 10,
    validFrom: "2026-03-01T00:00:00.000Z",
    validUntil: "2026-05-31T23:59:59.000Z",
    updatedAt: NOW,
  },
  {
    id: "price-bloom-tulip",
    supplierId: "supplier-bloom-trade",
    productSku: "flower-tulip-mix",
    productTitle: "Тюльпан микс",
    unit: "шт",
    purchasePriceRub: 45,
    minQuantity: 50,
    validFrom: "2026-03-01T00:00:00.000Z",
    validUntil: "2026-04-30T23:59:59.000Z",
    updatedAt: NOW,
  },
];

export const SUPPLIER_EXAMPLE_DELIVERY: SupplierDeliverySchedule[] = [
  {
    id: "delivery-flora-base",
    supplierId: "supplier-flora-moscow",
    zoneLabel: "Базовая зона",
    deliveryDays: 1,
    cutoffHour: 14,
    deliveryFeeRub: 0,
    isActive: true,
    updatedAt: NOW,
  },
  {
    id: "delivery-flora-7km",
    supplierId: "supplier-flora-moscow",
    zoneLabel: "До 7 км",
    deliveryDays: 1,
    cutoffHour: 12,
    deliveryFeeRub: 350,
    isActive: true,
    updatedAt: NOW,
  },
  {
    id: "delivery-bloom-base",
    supplierId: "supplier-bloom-trade",
    zoneLabel: "Базовая зона",
    deliveryDays: 2,
    cutoffHour: 16,
    deliveryFeeRub: 500,
    isActive: true,
    updatedAt: NOW,
  },
];

export const SUPPLIER_EXAMPLE_STOCK: SupplierStockEntry[] = [
  {
    id: "stock-flora-rose",
    supplierId: "supplier-flora-moscow",
    productSku: "flower-rose-red-60",
    productTitle: "Роза красная 60 см",
    availableQuantity: 500,
    status: "in_stock",
    restockEta: null,
    updatedAt: NOW,
  },
  {
    id: "stock-flora-peony",
    supplierId: "supplier-flora-moscow",
    productSku: "flower-peony-pink",
    productTitle: "Пион розовый",
    availableQuantity: 45,
    status: "low_stock",
    restockEta: "2026-04-01T00:00:00.000Z",
    updatedAt: NOW,
  },
  {
    id: "stock-bloom-tulip",
    supplierId: "supplier-bloom-trade",
    productSku: "flower-tulip-mix",
    productTitle: "Тюльпан микс",
    availableQuantity: 0,
    status: "out_of_stock",
    restockEta: "2026-03-20T00:00:00.000Z",
    updatedAt: NOW,
  },
];

export const SUPPLIER_EXAMPLE_CONTRACTS: SupplierContract[] = [
  {
    id: "contract-flora-2026",
    supplierId: "supplier-flora-moscow",
    title: "Flora Moscow Annual 2026",
    status: "active",
    startDate: "2026-01-01T00:00:00.000Z",
    endDate: "2026-12-31T23:59:59.000Z",
    paymentTermsDays: 14,
    discountPercent: 5,
    notes: "Preferred supplier agreement",
    createdAt: "2025-12-01T00:00:00.000Z",
    updatedAt: NOW,
  },
  {
    id: "contract-bloom-backup",
    supplierId: "supplier-bloom-trade",
    title: "Bloom Trade Backup SLA",
    status: "active",
    startDate: "2026-01-01T00:00:00.000Z",
    endDate: "2026-06-30T23:59:59.000Z",
    paymentTermsDays: 7,
    discountPercent: 0,
    notes: "Backup supplier for seasonal peaks",
    createdAt: "2025-12-15T00:00:00.000Z",
    updatedAt: NOW,
  },
];

export const SUPPLIER_EXAMPLE_HISTORY: SupplierHistoryEntry[] = [
  {
    id: "history-flora-order",
    supplierId: "supplier-flora-moscow",
    kind: "order",
    title: "Закупка роз",
    message: "500 шт роза красная 60 см",
    amountRub: 42500,
    occurredAt: "2026-06-18T09:00:00.000Z",
  },
  {
    id: "history-flora-delivery",
    supplierId: "supplier-flora-moscow",
    kind: "delivery",
    title: "Доставка выполнена",
    message: "On-time delivery, 1 day",
    amountRub: null,
    occurredAt: "2026-06-19T08:00:00.000Z",
  },
  {
    id: "history-bloom-price",
    supplierId: "supplier-bloom-trade",
    kind: "price_change",
    title: "Изменение цены",
    message: "Тюльпан микс +8%",
    amountRub: null,
    occurredAt: "2026-03-01T00:00:00.000Z",
  },
];

export const SUPPLIER_EXAMPLE_ANALYTICS: SupplierAnalyticsMetric[] = [
  {
    supplierId: "supplier-flora-moscow",
    totalOrders: 48,
    totalSpendRub: 1250000,
    onTimeDeliveryRate: 96,
    averageDeliveryDays: 1.1,
    priceStabilityScore: 88,
    stockAvailabilityRate: 92,
    calculatedAt: NOW,
  },
  {
    supplierId: "supplier-bloom-trade",
    totalOrders: 22,
    totalSpendRub: 380000,
    onTimeDeliveryRate: 82,
    averageDeliveryDays: 2.3,
    priceStabilityScore: 72,
    stockAvailabilityRate: 75,
    calculatedAt: NOW,
  },
  {
    supplierId: "supplier-green-pack",
    totalOrders: 15,
    totalSpendRub: 95000,
    onTimeDeliveryRate: 70,
    averageDeliveryDays: 3.2,
    priceStabilityScore: 65,
    stockAvailabilityRate: 68,
    calculatedAt: NOW,
  },
];

export const SUPPLIER_EXAMPLE_AI: SupplierAiPreparation[] = [
  {
    id: "ai-supplier-peony-backup",
    title: "Activate backup for peony shortage",
    rationale: "Flora Moscow peony low_stock — рассмотреть Bloom Trade",
    suggestedAction: "switch_to_backup_supplier",
    targetSupplierId: "supplier-bloom-trade",
    confidence: 0.81,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "ai-supplier-contract-renewal",
    title: "Renew Flora Moscow contract",
    rationale: "Contract expires Dec 2026 — начать переговоры Q3",
    suggestedAction: "schedule_contract_review",
    targetSupplierId: "supplier-flora-moscow",
    confidence: 0.74,
    status: "suggestion_only",
    createdAt: NOW,
  },
];

export function buildSupplierExampleRegistryState() {
  return {
    suppliers: [...SUPPLIER_EXAMPLE_SUPPLIERS],
    prices: [...SUPPLIER_EXAMPLE_PRICES],
    deliverySchedules: [...SUPPLIER_EXAMPLE_DELIVERY],
    stock: [...SUPPLIER_EXAMPLE_STOCK],
    contracts: [...SUPPLIER_EXAMPLE_CONTRACTS],
    history: [...SUPPLIER_EXAMPLE_HISTORY],
    analytics: [...SUPPLIER_EXAMPLE_ANALYTICS],
    aiPreparations: [...SUPPLIER_EXAMPLE_AI],
  };
}
