// ==================================================
// SECTION: RECOMMENDATION INTELLIGENCE
// РАЗДЕЛ: Seed examples (Stage 35 isolated)
// ==================================================
import type {
  RecommendationAiSuggestion,
  RecommendationHistoryEntry,
  RecommendationProductRef,
  RecommendationRule,
} from "@/components/recommendationIntelligence/recommendationTypes";

const NOW = new Date().toISOString();

export const RECOMMENDATION_EXAMPLE_PRODUCTS: RecommendationProductRef[] = [
  {
    productId: "product-rose-classic",
    title: "Классические розы",
    categoryIds: ["cat-bouquets"],
    flowerTypes: ["rose"],
    colors: ["red"],
    seasons: ["spring", "summer", "autumn"],
    basePriceRub: 4500,
    popularityScore: 92,
    isFeatured: true,
  },
  {
    productId: "product-rose-premium",
    title: "Premium розы",
    categoryIds: ["cat-premium", "cat-bouquets"],
    flowerTypes: ["rose"],
    colors: ["red", "white"],
    seasons: ["spring", "summer"],
    basePriceRub: 8900,
    popularityScore: 78,
    isFeatured: true,
  },
  {
    productId: "product-peony-premium",
    title: "Пионы Premium",
    categoryIds: ["cat-premium", "cat-seasonal"],
    flowerTypes: ["peony"],
    colors: ["pink", "white"],
    seasons: ["spring", "summer"],
    basePriceRub: 7200,
    popularityScore: 85,
    isFeatured: true,
  },
  {
    productId: "product-tulip-classic",
    title: "Весенние тюльпаны",
    categoryIds: ["cat-seasonal", "cat-bouquets"],
    flowerTypes: ["tulip"],
    colors: ["pink", "yellow"],
    seasons: ["spring"],
    basePriceRub: 3800,
    popularityScore: 70,
    isFeatured: false,
  },
];

export const RECOMMENDATION_EXAMPLE_RULES: RecommendationRule[] = [
  {
    id: "rule-related-products",
    kind: "related",
    title: "Related Products",
    description: "Сопутствующие товары на карточке продукта",
    priority: 10,
    maxResults: 4,
    minScore: 40,
    enabledSignals: ["similarity", "co_purchase", "popularity"],
    productIds: [],
    categoryIds: ["cat-bouquets"],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-similar-bouquets",
    kind: "similar",
    title: "Similar Bouquets",
    description: "Похожие букеты по цветам и цветам",
    priority: 12,
    maxResults: 4,
    minScore: 50,
    enabledSignals: ["similarity", "popularity"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-fbt",
    kind: "frequently_bought_together",
    title: "Frequently Bought Together",
    description: "Часто покупают вместе",
    priority: 15,
    maxResults: 3,
    minScore: 55,
    enabledSignals: ["co_purchase", "popularity"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-personalized",
    kind: "personalized",
    title: "Personalized Recommendations",
    description: "Персональные рекомendations по истории клиента",
    priority: 20,
    maxResults: 6,
    minScore: 45,
    enabledSignals: ["personal_history", "similarity", "popularity"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-seasonal",
    kind: "seasonal",
    title: "Seasonal Recommendations",
    description: "Сезонные рекомендации",
    priority: 8,
    maxResults: 5,
    minScore: 35,
    enabledSignals: ["seasonal", "popularity", "trending"],
    productIds: [],
    categoryIds: ["cat-seasonal"],
    seasons: ["spring"],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-trending",
    kind: "trending",
    title: "Trending Products",
    description: "Trending продукты",
    priority: 6,
    maxResults: 8,
    minScore: 30,
    enabledSignals: ["trending", "popularity"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-best-sellers",
    kind: "best_seller",
    title: "Best Sellers",
    description: "Лидеры продаж",
    priority: 5,
    maxResults: 10,
    minScore: 60,
    enabledSignals: ["popularity"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-recently-viewed",
    kind: "recently_viewed",
    title: "Recently Viewed",
    description: "Недавно просмотренные",
    priority: 4,
    maxResults: 6,
    minScore: 0,
    enabledSignals: ["personal_history"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "rule-ai",
    kind: "ai",
    title: "AI Recommendations",
    description: "AI-подготовка рекомендаций (foundation only)",
    priority: 25,
    maxResults: 5,
    minScore: 50,
    enabledSignals: ["similarity", "personal_history", "seasonal"],
    productIds: [],
    categoryIds: [],
    seasons: [],
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const RECOMMENDATION_EXAMPLE_HISTORY: RecommendationHistoryEntry[] = [
  {
    id: "rec-history-001",
    customerId: "customer-anna-ivanova",
    sessionId: "session-001",
    productId: "product-rose-classic",
    kind: "related",
    viewedAt: "2026-06-20T10:00:00.000Z",
    clicked: true,
    purchased: false,
  },
  {
    id: "rec-history-002",
    customerId: "customer-anna-ivanova",
    sessionId: "session-001",
    productId: "product-peony-premium",
    kind: "similar",
    viewedAt: "2026-06-20T10:05:00.000Z",
    clicked: true,
    purchased: true,
  },
  {
    id: "rec-history-003",
    customerId: null,
    sessionId: "session-002",
    productId: "product-tulip-classic",
    kind: "seasonal",
    viewedAt: "2026-06-21T14:00:00.000Z",
    clicked: false,
    purchased: false,
  },
];

export const RECOMMENDATION_EXAMPLE_AI: RecommendationAiSuggestion[] = [
  {
    id: "ai-rec-peony-upsell",
    customerId: "customer-anna-ivanova",
    productId: "product-peony-premium",
    title: "Upsell peony after rose view",
    rationale: "Клиент смотрел розы — предложить premium peony как upgrade",
    confidence: 0.82,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "ai-rec-spring-bundle",
    customerId: null,
    productId: "product-tulip-classic",
    title: "Spring bundle suggestion",
    rationale: "Сезон spring — связать tulip + peony в bundle recommendation",
    confidence: 0.75,
    status: "suggestion_only",
    createdAt: NOW,
  },
];

export const RECOMMENDATION_RELATED_MAP: Record<string, string[]> = {
  "product-rose-classic": ["product-rose-premium"],
  "product-rose-premium": ["product-rose-classic"],
  "product-peony-premium": ["product-tulip-classic"],
  "product-tulip-classic": ["product-peony-premium"],
};

export const RECOMMENDATION_FBT_MAP: Record<string, string[]> = {
  "product-rose-classic": ["product-rose-premium", "product-peony-premium"],
  "product-peony-premium": ["product-rose-classic"],
};

export function buildRecommendationExampleRegistryState() {
  return {
    rules: [...RECOMMENDATION_EXAMPLE_RULES],
    products: [...RECOMMENDATION_EXAMPLE_PRODUCTS],
    history: [...RECOMMENDATION_EXAMPLE_HISTORY],
    aiSuggestions: [...RECOMMENDATION_EXAMPLE_AI],
  };
}
