// ==================================================
// SECTION: CATALOG INTELLIGENCE
// РАЗДЕЛ: Seed examples
// ==================================================
import type {
  CatalogAiProductSuggestion,
  CatalogAvailabilityEntry,
  CatalogCategoryRecord,
  CatalogFeaturedEntry,
  CatalogProductGroup,
  CatalogProductRecord,
  CatalogSearchIndexEntry,
  CatalogSmartCategory,
  CatalogSmartCollection,
} from "@/components/catalogIntelligence/catalogTypes";

const NOW = new Date().toISOString();

export const CATALOG_EXAMPLE_CATEGORIES: CatalogCategoryRecord[] = [
  {
    id: "cat-bouquets",
    slug: "bouquets",
    title: "Букеты",
    description: "Классические и авторские букеты",
    parentId: null,
    productCount: 4,
    sortOrder: 1,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "cat-premium",
    slug: "premium",
    title: "Premium",
    description: "Премиальные композиции",
    parentId: null,
    productCount: 2,
    sortOrder: 2,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "cat-seasonal",
    slug: "seasonal",
    title: "Сезонные",
    description: "Сезонные коллекции",
    parentId: null,
    productCount: 2,
    sortOrder: 3,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_SMART_CATEGORIES: CatalogSmartCategory[] = [
  {
    id: "smart-romantic",
    slug: "romantic",
    title: "Romantic",
    description: "Романтичные букеты для особых моментов",
    ruleTags: ["romantic", "gift"],
    ruleCategoryIds: ["cat-bouquets"],
    ruleSeasons: ["spring", "summer"],
    productIds: ["product-rose-classic", "product-peony-premium"],
    sortOrder: 1,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "smart-spring-bloom",
    slug: "spring-bloom",
    title: "Spring Bloom",
    description: "Весенние цветы и сезонные композиции",
    ruleTags: ["seasonal", "spring"],
    ruleCategoryIds: ["cat-seasonal"],
    ruleSeasons: ["spring"],
    productIds: ["product-tulip-classic", "product-peony-premium"],
    sortOrder: 2,
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_COLLECTIONS: CatalogSmartCollection[] = [
  {
    id: "collection-popular",
    slug: "popular",
    title: "Popular Products",
    description: "Самые популярные букеты",
    kind: "popular",
    productIds: ["product-rose-classic", "product-peony-premium", "product-tulip-classic"],
    categoryIds: ["cat-bouquets"],
    season: null,
    badge: "Popular",
    sortOrder: 1,
    isPublished: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "collection-spring",
    slug: "spring-collection",
    title: "Spring Collection",
    description: "Сезонная весенняя коллекция",
    kind: "seasonal",
    productIds: ["product-tulip-classic", "product-peony-premium"],
    categoryIds: ["cat-seasonal"],
    season: "spring",
    badge: "Seasonal",
    sortOrder: 2,
    isPublished: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "collection-featured",
    slug: "featured",
    title: "Featured Catalog",
    description: "Избранные позиции каталога",
    kind: "featured",
    productIds: ["product-peony-premium", "product-rose-premium"],
    categoryIds: ["cat-premium"],
    season: null,
    badge: "Featured",
    sortOrder: 3,
    isPublished: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_PRODUCT_GROUPS: CatalogProductGroup[] = [
  {
    id: "group-roses",
    title: "Rose Bouquets",
    description: "Группа розовых букетов",
    productIds: ["product-rose-classic", "product-rose-premium"],
    leaderProductId: "product-rose-classic",
    tags: ["rose", "romantic"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "group-peonies",
    title: "Peony Collection",
    description: "Пионы и сезонные композиции",
    productIds: ["product-peony-premium"],
    leaderProductId: "product-peony-premium",
    tags: ["peony", "seasonal"],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_PRODUCTS: CatalogProductRecord[] = [
  {
    id: "product-rose-classic",
    slug: "rose-classic",
    title: "Классические розы",
    shortDescription: "25 красных роз в классической упаковке",
    categoryIds: ["cat-bouquets"],
    groupId: "group-roses",
    tags: ["romantic", "classic", "gift"],
    colors: ["red"],
    flowerTypes: ["rose"],
    occasions: ["romantic", "anniversary"],
    seasons: ["spring", "summer", "autumn"],
    basePriceRub: 4500,
    popularityScore: 92,
    seasonalScore: 40,
    availability: "in_stock",
    status: "published",
    isFeatured: true,
    isSeasonal: false,
    relatedProductIds: ["product-rose-premium"],
    similarProductIds: ["product-peony-premium"],
    searchTerms: ["розы", "красные", "romantic", "classic"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "product-rose-premium",
    slug: "rose-premium",
    title: "Premium розы",
    shortDescription: "51 роза премиум-класса",
    categoryIds: ["cat-premium", "cat-bouquets"],
    groupId: "group-roses",
    tags: ["premium", "romantic", "vip"],
    colors: ["red", "white"],
    flowerTypes: ["rose"],
    occasions: ["wedding", "vip"],
    seasons: ["spring", "summer"],
    basePriceRub: 8900,
    popularityScore: 78,
    seasonalScore: 35,
    availability: "in_stock",
    status: "published",
    isFeatured: true,
    isSeasonal: false,
    relatedProductIds: ["product-rose-classic"],
    similarProductIds: ["product-peony-premium"],
    searchTerms: ["premium", "розы", "vip"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "product-peony-premium",
    slug: "peony-premium",
    title: "Пионы Premium",
    shortDescription: "Авторский букет из пионов",
    categoryIds: ["cat-premium", "cat-seasonal"],
    groupId: "group-peonies",
    tags: ["peony", "seasonal", "premium"],
    colors: ["pink", "white"],
    flowerTypes: ["peony"],
    occasions: ["birthday", "gift"],
    seasons: ["spring", "summer"],
    basePriceRub: 7200,
    popularityScore: 85,
    seasonalScore: 95,
    availability: "seasonal",
    status: "published",
    isFeatured: true,
    isSeasonal: true,
    relatedProductIds: ["product-tulip-classic"],
    similarProductIds: ["product-rose-classic", "product-rose-premium"],
    searchTerms: ["пионы", "peony", "spring", "premium"],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: "product-tulip-classic",
    slug: "tulip-classic",
    title: "Весенние тюльпаны",
    shortDescription: "Яркий букет из тюльпанов",
    categoryIds: ["cat-seasonal", "cat-bouquets"],
    groupId: null,
    tags: ["tulip", "seasonal", "spring"],
    colors: ["pink", "yellow"],
    flowerTypes: ["tulip"],
    occasions: ["gift", "spring"],
    seasons: ["spring"],
    basePriceRub: 3800,
    popularityScore: 70,
    seasonalScore: 90,
    availability: "in_stock",
    status: "published",
    isFeatured: false,
    isSeasonal: true,
    relatedProductIds: ["product-peony-premium"],
    similarProductIds: ["product-peony-premium"],
    searchTerms: ["тюльпаны", "tulip", "spring"],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_FEATURED: CatalogFeaturedEntry[] = [
  {
    productId: "product-rose-classic",
    badge: "Popular",
    sortOrder: 1,
    highlightUntil: null,
    collectionId: "collection-popular",
  },
  {
    productId: "product-peony-premium",
    badge: "Featured",
    sortOrder: 2,
    highlightUntil: "2026-08-31T23:59:59.000Z",
    collectionId: "collection-featured",
  },
  {
    productId: "product-rose-premium",
    badge: "Premium",
    sortOrder: 3,
    highlightUntil: null,
    collectionId: "collection-featured",
  },
];

export const CATALOG_EXAMPLE_AVAILABILITY: CatalogAvailabilityEntry[] = [
  {
    productId: "product-rose-classic",
    status: "in_stock",
    stockHint: 25,
    restockEta: null,
    updatedAt: NOW,
  },
  {
    productId: "product-rose-premium",
    status: "in_stock",
    stockHint: 12,
    restockEta: null,
    updatedAt: NOW,
  },
  {
    productId: "product-peony-premium",
    status: "seasonal",
    stockHint: 8,
    restockEta: "2026-04-01T00:00:00.000Z",
    updatedAt: NOW,
  },
  {
    productId: "product-tulip-classic",
    status: "low_stock",
    stockHint: 3,
    restockEta: "2026-03-20T00:00:00.000Z",
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_SEARCH_INDEX: CatalogSearchIndexEntry[] = [
  {
    id: "index-rose-title",
    productId: "product-rose-classic",
    token: "розы",
    weight: 10,
    source: "title",
    updatedAt: NOW,
  },
  {
    id: "index-rose-flower",
    productId: "product-rose-classic",
    token: "rose",
    weight: 8,
    source: "flower",
    updatedAt: NOW,
  },
  {
    id: "index-peony-title",
    productId: "product-peony-premium",
    token: "пионы",
    weight: 10,
    source: "title",
    updatedAt: NOW,
  },
  {
    id: "index-tulip-season",
    productId: "product-tulip-classic",
    token: "spring",
    weight: 6,
    source: "tag",
    updatedAt: NOW,
  },
];

export const CATALOG_EXAMPLE_AI_SUGGESTIONS: CatalogAiProductSuggestion[] = [
  {
    id: "ai-suggest-peony-upsell",
    productId: "product-peony-premium",
    title: "Upsell peony premium in spring",
    rationale: "Высокий seasonal score — рекомендовать в весенней коллекции",
    confidence: 0.84,
    status: "suggestion_only",
    createdAt: NOW,
  },
  {
    id: "ai-suggest-rose-bundle",
    productId: "product-rose-classic",
    title: "Bundle classic + premium roses",
    rationale: "Связанные продукты в одной группе — предложить upgrade",
    confidence: 0.71,
    status: "suggestion_only",
    createdAt: NOW,
  },
];

export function buildCatalogExampleRegistryState() {
  return {
    smartCategories: [...CATALOG_EXAMPLE_SMART_CATEGORIES],
    categories: [...CATALOG_EXAMPLE_CATEGORIES],
    collections: [...CATALOG_EXAMPLE_COLLECTIONS],
    productGroups: [...CATALOG_EXAMPLE_PRODUCT_GROUPS],
    products: [...CATALOG_EXAMPLE_PRODUCTS],
    featured: [...CATALOG_EXAMPLE_FEATURED],
    availability: [...CATALOG_EXAMPLE_AVAILABILITY],
    searchIndex: [...CATALOG_EXAMPLE_SEARCH_INDEX],
    aiSuggestions: [...CATALOG_EXAMPLE_AI_SUGGESTIONS],
  };
}
