// ==================================================
// SECTION: CATALOG INTELLIGENCE
// РАЗДЕЛ: Public foundation exports
// ==================================================
export type {
  CatalogSeason,
  CatalogAvailabilityStatus,
  CatalogProductStatus,
  CatalogFilterKind,
  CatalogCollectionKind,
  CatalogAiSuggestionStatus,
  CatalogSmartCategory,
  CatalogSmartCollection,
  CatalogProductGroup,
  CatalogProductRecord,
  CatalogCategoryRecord,
  CatalogSearchIndexEntry,
  CatalogFilterOption,
  CatalogFilterGroup,
  CatalogAvailabilityEntry,
  CatalogFeaturedEntry,
  CatalogAiProductSuggestion,
  CatalogStatistics,
  CatalogIntelligenceSnapshot,
  CatalogListFilters,
  CatalogRegistryState,
  CatalogReadOnlySummary,
  CatalogRelatedProductsResult,
  CatalogSearchResult,
} from "@/components/catalogIntelligence/catalogTypes";

export {
  CATALOG_EXAMPLE_CATEGORIES,
  CATALOG_EXAMPLE_SMART_CATEGORIES,
  CATALOG_EXAMPLE_COLLECTIONS,
  CATALOG_EXAMPLE_PRODUCT_GROUPS,
  CATALOG_EXAMPLE_PRODUCTS,
  CATALOG_EXAMPLE_FEATURED,
  CATALOG_EXAMPLE_AVAILABILITY,
  CATALOG_EXAMPLE_SEARCH_INDEX,
  CATALOG_EXAMPLE_AI_SUGGESTIONS,
  buildCatalogExampleRegistryState,
} from "@/components/catalogIntelligence/catalogExamples";

export {
  CATALOG_CATEGORY_STORAGE_KEY,
  CATALOG_SMART_CATEGORY_STORAGE_KEY,
  listCatalogCategories,
  getCatalogCategoryById,
  getCatalogCategoryBySlug,
  listSmartCategories,
  getSmartCategoryById,
  listSmartCategoriesBySeason,
  registerCatalogCategory,
  registerSmartCategory,
  seedCatalogCategoryRegistry,
  clearCatalogCategoryRegistry,
} from "@/components/catalogIntelligence/catalogCategoryRegistry";

export {
  CATALOG_PRODUCT_STORAGE_KEY,
  CATALOG_COLLECTION_STORAGE_KEY,
  CATALOG_GROUP_STORAGE_KEY,
  CATALOG_FEATURED_STORAGE_KEY,
  CATALOG_AVAILABILITY_STORAGE_KEY,
  listCatalogProducts,
  getCatalogProductById,
  getCatalogProductBySlug,
  listPopularProducts,
  listSeasonalProducts,
  listFeaturedCatalogProducts,
  listSmartCollections,
  getSmartCollectionById,
  listProductsByCollection,
  listProductGroups,
  getProductGroupById,
  listProductsByGroup,
  getRelatedProducts,
  getSimilarBouquets,
  listAvailabilityRegistry,
  getProductAvailability,
  listProductsByAvailability,
  listFeaturedEntries,
  registerCatalogProduct,
  seedCatalogProductRegistry,
  clearCatalogProductRegistry,
} from "@/components/catalogIntelligence/catalogProductRegistry";

export {
  CATALOG_SEARCH_INDEX_STORAGE_KEY,
  CATALOG_AI_SUGGESTIONS_STORAGE_KEY,
  listSearchIndexEntries,
  listSearchIndexByProduct,
  buildSearchIndexFromProducts,
  searchCatalog,
  buildCatalogFilters,
  listCatalogFilterOptions,
  listAiProductSuggestions,
  getAiProductSuggestionById,
  registerSearchIndexEntry,
  registerAiProductSuggestion,
  seedCatalogSearchRegistry,
  rebuildCatalogSearchIndex,
  clearCatalogSearchRegistry,
} from "@/components/catalogIntelligence/catalogSearchRegistry";

export {
  CATALOG_INTELLIGENCE_STORAGE_KEY,
  calculateCatalogStatistics,
  buildCatalogIntelligenceSnapshot,
  initializeCatalogIntelligence,
  getCatalogIntelligenceExample,
  getCatalogReadOnlySummary,
  readRelatedAndSimilarProducts,
  listAllCatalogFoundationCapabilities,
  CATALOG_INTELLIGENCE_ENGINE_SCHEMA,
} from "@/components/catalogIntelligence/catalogEngine";
